# core/config.sh - 全定数・パス定義・mkdir初期化
#
# ELOOP_LIB_DIR は eloop_lib.sh (shim) で設定済み。
# このファイルでは再設定しない。

# --- 定数 ---
COMMANDS="commands.txt"
GAME_STATE="game_state.json"

STRATEGY_FILE="strategy.py"
STRATEGY_VERSIONS_DIR="strategy_versions"
HISTORY_DIR="game_history"
HISTORY_FILE="$HISTORY_DIR/latest.jsonl"
PHYROGENETIC_TREE_FILE="phyrogenetic-tree.md"
PHYROGENETIC_EVENTS_FILE="phyrogenetic-events.jsonl"
PHYROGENETIC_TREE_URL="${PHYROGENETIC_TREE_URL:-https://github.com/azumag/soviet_now/blob/main/phyrogenetic-tree.md}"

MODEL_IMPROVE="${MODEL_IMPROVE:-opencode:minimax}"
REGRESSION_DISABLED=0
MERIKEN_SCHEDULED_TIME_ENABLED=0 # 20-21時メリケンAIタイムを無効化
MODEL_FALLBACK_IMPROVE="opencode:nvdeepseekv4pro"
MODEL_LAST_RESORT="opencode:glmflash"

GAME_COUNT_FILE="game_count.txt"

RADIO_MAIN_AGENT="${RADIO_MAIN_AGENT:-opencode:qwen35pgo}"
RADIO_MAIN_PREPASS_AGENT="${RADIO_MAIN_PREPASS_AGENT:-opencode:minimax}"
RADIO_MAIN_FALLBACK="qwen35e"
RADIO_MAIN_OLLAMA_FALLBACK="opencode:glmflash"
RADIO_OPENCODE_DEFER_DURING_IMPROVE="${RADIO_OPENCODE_DEFER_DURING_IMPROVE:-1}"
RADIO_OPENCODE_TIMEOUT=240
OLLAMA_BASE_URL="${OLLAMA_BASE_URL:-http://192.168.11.3:11434}"
RADIO_OLLAMA_MODEL="${RADIO_OLLAMA_MODEL:-qwen3.5:9b}"
RADIO_OLLAMA_TIMEOUT="${RADIO_OLLAMA_TIMEOUT:-300}"
COMMENT_OLLAMA_MODEL="${COMMENT_OLLAMA_MODEL:-qwen3.5:9b}"
COMMENT_OLLAMA_MODEL_IMPROVING="${COMMENT_OLLAMA_MODEL_IMPROVING:-gemma4:latest}"
COMMENT_OLLAMA_TIMEOUT="${COMMENT_OLLAMA_TIMEOUT:-60}"
COMMENT_MAIN_AGENT="${COMMENT_MAIN_AGENT:-opencode:qwen35pgo}"
COMMENT_CLASSIFIER_AGENT="${COMMENT_CLASSIFIER_AGENT:-minimax}"
COMMENT_CLASSIFIER_FALLBACK="${COMMENT_CLASSIFIER_FALLBACK:-opencode:qwen35pgo}"
COMMENT_CLASSIFIER_EDIT_AGENT="${COMMENT_CLASSIFIER_EDIT_AGENT:-minimax}"
COMMENT_CLASSIFIER_EDIT_FALLBACK="${COMMENT_CLASSIFIER_EDIT_FALLBACK:-opencode:qwen35pgo}"
COMMENT_CLASSIFIER_EDIT_TIMEOUT="${COMMENT_CLASSIFIER_EDIT_TIMEOUT:-45}"
COMMENT_CLASSIFIER_TIMEOUT="${COMMENT_CLASSIFIER_TIMEOUT:-90}"
COMMENT_CLASSIFIER_AI_ENABLED="${COMMENT_CLASSIFIER_AI_ENABLED:-0}"
COMMENT_CLASSIFIER_OPENCODE_PERMISSION_DEFAULT='{"*":"deny","read":"allow","glob":"allow","grep":"allow","list":"allow","edit":"allow","write":"allow","external_directory":"allow"}'
COMMENT_CLASSIFIER_OPENCODE_PERMISSION="${COMMENT_CLASSIFIER_OPENCODE_PERMISSION:-$COMMENT_CLASSIFIER_OPENCODE_PERMISSION_DEFAULT}"
COMMENT_MAIN_FALLBACK="qwen35e"
COMMENT_MAIN_OLLAMA_FALLBACK="opencode:glmflash"
COMMENT_MAIN_ALLOW_CLAUDE_FALLBACK="${COMMENT_MAIN_ALLOW_CLAUDE_FALLBACK:-1}"
COMMENT_SOREN91_AGENT="${COMMENT_SOREN91_AGENT:-haiku}"
COMMENT_SOREN91_FALLBACK="${COMMENT_SOREN91_FALLBACK:-gemma4e}"
RADIO_SOREN91_AGENT="${RADIO_SOREN91_AGENT:-haiku}"
RADIO_SOREN91_FALLBACK="${RADIO_SOREN91_FALLBACK:-gemma4e}"
COMMENT_GENERATION_HISTORY_FILE="${TMP_HISTORY_DIR:-tmp/history}/comment_generation_history.jsonl"
RADIO_GENERATION_HISTORY_FILE="${TMP_HISTORY_DIR:-tmp/history}/radio_generation_history.jsonl"
COMMENT_GENERATION_HISTORY_KEEP="${COMMENT_GENERATION_HISTORY_KEEP:-500}"
RADIO_GENERATION_HISTORY_KEEP="${RADIO_GENERATION_HISTORY_KEEP:-500}"
RADIO_CLAUDE_MODEL="${RADIO_CLAUDE_MODEL:-haiku}"
RADIO_BRIEFING_ENABLED="${RADIO_BRIEFING_ENABLED:-0}"
RADIO_BRIEFING_MAX_CHARS="${RADIO_BRIEFING_MAX_CHARS:-2000}"
RADIO_BRIEFING_MODEL="${RADIO_BRIEFING_MODEL:-claude-haiku-4-5-20251001}"
RADIO_QUALITY_CHECK_ENABLED="${RADIO_QUALITY_CHECK_ENABLED:-1}"
RADIO_MAX_RETRIES="${RADIO_MAX_RETRIES:-1}"
RADIO_QUALITY_MIN_JAPANESE_RATIO="${RADIO_QUALITY_MIN_JAPANESE_RATIO:-0.10}"
RADIO_QUALITY_MAX_REPETITIONS="${RADIO_QUALITY_MAX_REPETITIONS:-3}"
RADIO_QUALITY_SKIP_CORNERS="${RADIO_QUALITY_SKIP_CORNERS:-}"
RADIO_FACT_CHECK_ENABLED="${RADIO_FACT_CHECK_ENABLED:-1}"
RUSSIA_CELEBRATION_ENABLED="${RUSSIA_CELEBRATION_ENABLED:-0}"
ROLLBACK_POSTMORTEM_MODEL="opencode:qwen35e"
ROLLBACK_POSTMORTEM_FALLBACK="opencode:glmflash"
ROLLBACK_POSTMORTEM_TIMEOUT_SEC="${ROLLBACK_POSTMORTEM_TIMEOUT_SEC:-300}"
# 粛清カスケード中 (regression_streak >= 閾値) は AI postmortem をスキップし
# opencode スロット競合を減らして改善サイクル長期化=代打無限化を防ぐ
ROLLBACK_POSTMORTEM_CASCADE_SKIP_ENABLED="${ROLLBACK_POSTMORTEM_CASCADE_SKIP_ENABLED:-1}"
ROLLBACK_POSTMORTEM_CASCADE_SKIP_STREAK="${ROLLBACK_POSTMORTEM_CASCADE_SKIP_STREAK:-2}"
# 改善完了後、次の (カスケード) 改善ロックに即 PAUSE する前にメインゲームを
# 最低1ゲーム走らせる窓。soren91 代打がサイクル間で連続起動し続けるのを防ぐ
# strategy_runner が commands未消化 N連続で bridge desync を検出した時、
# eloop.sh が bridge を自動再起動して空転を自己回復する
BRIDGE_DESYNC_AUTO_RECOVER_ENABLED="${BRIDGE_DESYNC_AUTO_RECOVER_ENABLED:-1}"
BRIDGE_DESYNC_STOP_STALE_SOREN91_ENABLED="${BRIDGE_DESYNC_STOP_STALE_SOREN91_ENABLED:-1}"
BRIDGE_DESYNC_SOREN91_STOP_TIMEOUT="${BRIDGE_DESYNC_SOREN91_STOP_TIMEOUT:-0}"
PHANTOM_GAME_AUTO_RECOVER_ENABLED="${PHANTOM_GAME_AUTO_RECOVER_ENABLED:-1}"
SOREN_BRIDGE_DESYNC_LIMIT="${SOREN_BRIDGE_DESYNC_LIMIT:-6}"
POST_IMPROVE_MAINPLAY_ENABLED="${POST_IMPROVE_MAINPLAY_ENABLED:-1}"
# TMP_STATE_DIR は後方で定義されるためリテラル指定 (= tmp/state)
POST_IMPROVE_MAINPLAY_MARKER="tmp/state/.post_improve_mainplay"
RADIO_FACT_CHECK_AGENT="${RADIO_FACT_CHECK_AGENT:-opencode:glmflash}"
RADIO_FACT_CHECK_FALLBACK="${RADIO_FACT_CHECK_FALLBACK:-zai}"
RADIO_FACT_CHECK_CLAUDE_MODEL="${RADIO_FACT_CHECK_CLAUDE_MODEL:-$RADIO_CLAUDE_MODEL}"
RADIO_FACT_CHECK_MIN_CHARS=100
RADIO_FACT_CHECK_SKIP_CORNERS="${RADIO_FACT_CHECK_SKIP_CORNERS:-strategy}"
RADIO_FACT_CHECK_MIN_RATIO="${RADIO_FACT_CHECK_MIN_RATIO:-0.68}"
RADIO_FACT_CHECK_MAX_ABS_SHRINK="${RADIO_FACT_CHECK_MAX_ABS_SHRINK:-700}"
RADIO_FACT_CHECK_FEW_ISSUES_MAX="${RADIO_FACT_CHECK_FEW_ISSUES_MAX:-2}"
RADIO_FACT_CHECK_MIN_SIMILARITY_NOISSUES="${RADIO_FACT_CHECK_MIN_SIMILARITY_NOISSUES:-0.90}"
RADIO_FACT_CHECK_MIN_SIMILARITY_FEW_ISSUES="${RADIO_FACT_CHECK_MIN_SIMILARITY_FEW_ISSUES:-0.74}"
RADIO_FACT_CHECK_MAX_PARAGRAPH_DROP="${RADIO_FACT_CHECK_MAX_PARAGRAPH_DROP:-2}"
RADIO_WEB_GROUNDING_ENABLED="${RADIO_WEB_GROUNDING_ENABLED:-1}"
RADIO_WEB_GROUNDING_TTL_SEC="${RADIO_WEB_GROUNDING_TTL_SEC:-21600}"
RADIO_WEB_GROUNDING_MAX_SOURCES="${RADIO_WEB_GROUNDING_MAX_SOURCES:-3}"
RADIO_STATE_STALE_SEC="${RADIO_STATE_STALE_SEC:-600}"
# --- tmp/ サブディレクトリ ---
TMP_STATE_DIR="tmp/state"
TMP_MARKERS_DIR="tmp/markers"
TMP_HISTORY_DIR="tmp/history"
TMP_DEBUG_DIR="tmp/debug"
TMP_CACHE_DIR="tmp/cache"
CC_POST_LOG_FILE="$TMP_DEBUG_DIR/cc_post.log"
PHYROGENETIC_CHAT_POST_LOG_FILE="$TMP_DEBUG_DIR/phyrogenetic_chat_post.log"

RADIO_WEB_GROUNDING_CACHE_DIR="$TMP_CACHE_DIR/radio_grounding"
RADIO_STATE_FILE="$TMP_STATE_DIR/.radio_state"
RADIO_THEME_PICK_STATUS_FILE="$TMP_STATE_DIR/.radio_theme_pick_status.json"
RADIO_CORNER_STATUS_FILE="$TMP_STATE_DIR/.radio_corner_status.json"
COMMENT_GEN_STATE_FILE="$TMP_STATE_DIR/.comment_gen_state"
LAST_PHYROGENETIC_CHAT_COMMIT_FILE="$TMP_STATE_DIR/last_phyrogenetic_chat_commit.txt"
MANUAL_MERIKEN_MODE_FILE="$TMP_STATE_DIR/manual_meriken_mode.json"
RADIO_OPENCODE_PERMISSION='{"*":"deny","read":"allow","glob":"allow","grep":"allow","list":"allow","webfetch":"allow","web-search":"allow","external_directory":"allow"}'
COMMENT_OPENCODE_PERMISSION_DEFAULT='{"*":"deny","read":"allow","glob":"allow","grep":"allow","list":"allow","web":"allow","web-search":"allow","external_directory":"allow"}'
COMMENT_OPENCODE_PERMISSION="${COMMENT_OPENCODE_PERMISSION:-$COMMENT_OPENCODE_PERMISSION_DEFAULT}"
COMMENT_OPENCODE_TIMEOUT="${COMMENT_OPENCODE_TIMEOUT:-240}"
COMMENT_CLAUDE_TOOLS="${COMMENT_CLAUDE_TOOLS:-default,WebSearch,WebFetch}"
COMMENT_CLAUDE_TIMEOUT="${COMMENT_CLAUDE_TIMEOUT:-180}"
COMMENT_TRY_CLAUDE_BEFORE_OPENCODE_FALLBACK="${COMMENT_TRY_CLAUDE_BEFORE_OPENCODE_FALLBACK:-0}"
COMMENT_FORCE_CLAUDE_WHEN_IMPROVING="${COMMENT_FORCE_CLAUDE_WHEN_IMPROVING:-1}"
IMPROVE_OPENCODE_PERMISSION='{"*":"deny","read":"allow","glob":"allow","grep":"allow","list":"allow","edit":"allow","write":"allow","external_directory":"allow"}'
RADIO_SAY_RATE=150
unset SAY_AUDIO_DEVICE
PAST_RADIO_TOPICS="$TMP_HISTORY_DIR/past_radio_topics.txt"
PAST_RADIO_THEME_KEYS="$TMP_HISTORY_DIR/.past_radio_themes.txt"
PAST_RADIO_THEME_BODIES="$TMP_HISTORY_DIR/past_radio_theme_bodies.txt"
PAST_RADIO_THEME_HISTORY_KEEP="${PAST_RADIO_THEME_HISTORY_KEEP:-400}"
PAST_NEWS_READ="$TMP_HISTORY_DIR/past_news_read.txt"
PAST_NEWS_READ_KEYS="$TMP_HISTORY_DIR/past_news_read_keys.txt"
PAST_NEWS_URL_HASHES="$TMP_HISTORY_DIR/past_news_url_hashes.txt"
PAST_NEWS_TOPIC_KEYS="$TMP_HISTORY_DIR/past_news_topic_keys.txt"
PAST_JIJI_URL_HASHES="$TMP_HISTORY_DIR/past_jiji_url_hashes.txt"
PAST_NEWS_READ_SOURCES="$TMP_HISTORY_DIR/past_news_read_sources.txt"
RUSSIA_CREATION_HISTORY_FILE="$TMP_HISTORY_DIR/russia_creation_history.tsv"
SOVIET_CREATION_HISTORY_FILE="$TMP_HISTORY_DIR/soviet_creation_history.tsv"
CELEBRATION_HISTORY_KEEP_LINES="${CELEBRATION_HISTORY_KEEP_LINES:-200}"
COMMENT_CELEBRATION_HISTORY_ITEMS="${COMMENT_CELEBRATION_HISTORY_ITEMS:-12}"
MAIN_STRATEGY_ADVICE_FILE="advice.md"
SOREN91_STRATEGY_ADVICE_FILE="advice91.md"
COMMENT_ADVICE_FILE="advice_comment.md"
STRATEGY_ADVICE_FILE="$MAIN_STRATEGY_ADVICE_FILE"

IMPROVE_STATE_FILE="$ELOOP_LIB_DIR/$TMP_STATE_DIR/improve_state.json"
IMPROVE_LOCK_FILE="$ELOOP_LIB_DIR/tmp/improve.lock"
# spawn 排他 mutex: dual-spawner (soren_loop 本流 + improve_daemon watchdog) の
# 二重起動レースを mkdir atomic で防ぐ。owner ファイルで所有者検証付き。
IMPROVE_SPAWN_LOCK_DIR="$ELOOP_LIB_DIR/$TMP_STATE_DIR/.improve_spawn.lock"
IMPROVE_SPAWN_LOCK_TTL="${IMPROVE_SPAWN_LOCK_TTL:-90}"
# Fix0: 復旧アクター調停 (guardian / _ensure_bridge_alive / soviet_watchdog 共通)
RUNTIME_RECOVERY_LOCK_DIR="$ELOOP_LIB_DIR/$TMP_STATE_DIR/.runtime_recovery.lock"
RUNTIME_RECOVERY_LOCK_TTL="${RUNTIME_RECOVERY_LOCK_TTL:-120}"
RUNTIME_RECOVERY_TAINT_FILE="$ELOOP_LIB_DIR/$TMP_STATE_DIR/runtime_recovery.taint"
RUNTIME_RECOVERY_TAINT_WINDOW="${RUNTIME_RECOVERY_TAINT_WINDOW:-180}"
IMPROVE_DAEMON_PID_FILE="$TMP_STATE_DIR/improve_daemon.pid"
IMPROVE_AI_LOG_FILE="$ELOOP_LIB_DIR/$TMP_DEBUG_DIR/improve_ai.log"
IMPROVE_OVERLAY_HTML_FILE="$ELOOP_LIB_DIR/$TMP_STATE_DIR/improve_overlay.html"
IMPROVE_OVERLAY_LOG_FILE="$ELOOP_LIB_DIR/$TMP_DEBUG_DIR/improve_overlay.log"
IMPROVE_OVERLAY_SOURCE="${OBS_IMPROVE_OVERLAY_SOURCE:-improveOverlay}"
IMPROVE_OVERLAY_REFRESH_SEC="${IMPROVE_OVERLAY_REFRESH_SEC:-2}"
IMPROVE_FAST_ESCAPE_OVERLAY_HOLD_SEC="${IMPROVE_FAST_ESCAPE_OVERLAY_HOLD_SEC:-45}"
EVENT_OVERLAY_EVENTS_FILE="$ELOOP_LIB_DIR/$TMP_STATE_DIR/overlay_events.jsonl"
EVENT_OVERLAY_HTML_FILE="$ELOOP_LIB_DIR/$TMP_STATE_DIR/event_overlay.html"
EVENT_OVERLAY_KEEP_EVENTS="${EVENT_OVERLAY_KEEP_EVENTS:-180}"
EVENT_OVERLAY_VISIBLE_SEC="${EVENT_OVERLAY_VISIBLE_SEC:-18}"
EVENT_OVERLAY_SOURCE="${OBS_EVENT_OVERLAY_SOURCE:-eventOverlay}"
CODEX_WORK_OVERLAY_STATE_FILE="$ELOOP_LIB_DIR/$TMP_STATE_DIR/codex_work_indicator.json"
STATUS_OVERLAY_HTML_FILE="$ELOOP_LIB_DIR/$TMP_STATE_DIR/status_overlay.html"
STATUS_OVERLAY_SOURCE="${STATUS_OVERLAY_SOURCE:-${OBS_STATS_OVERLAY_SOURCE:-${OBS_STATUS_OVERLAY_SOURCE:-statsOverlay}}}"
STATS_OVERLAY_SOURCE="$STATUS_OVERLAY_SOURCE"
STATUS_OVERLAY_WIDTH="${STATUS_OVERLAY_WIDTH:-640}"
STATUS_OVERLAY_HEIGHT="${STATUS_OVERLAY_HEIGHT:-920}"
STATUS_OVERLAY_OBS_X="${STATUS_OVERLAY_OBS_X:-24}"
STATUS_OVERLAY_OBS_Y="${STATUS_OVERLAY_OBS_Y:-300}"
STATUS_OVERLAY_OBS_SCALE_X="${STATUS_OVERLAY_OBS_SCALE_X:-0.86}"
STATUS_OVERLAY_OBS_SCALE_Y="${STATUS_OVERLAY_OBS_SCALE_Y:-0.78}"
STATUS_OVERLAY_OBS_TRANSFORM_ENABLED="${STATUS_OVERLAY_OBS_TRANSFORM_ENABLED:-1}"
SHOW_STATUS_OVERLAY_HTML_FILE="$ELOOP_LIB_DIR/$TMP_STATE_DIR/show_status_overlay.html"
SHOW_STATUS_OVERLAY_SOURCE="${SHOW_STATUS_OVERLAY_SOURCE:-${OBS_OPS_OVERLAY_SOURCE:-${OBS_SHOW_STATUS_OVERLAY_SOURCE:-opsOverlay}}}"
OPS_OVERLAY_SOURCE="$SHOW_STATUS_OVERLAY_SOURCE"
SHOW_STATUS_OVERLAY_WIDTH="${SHOW_STATUS_OVERLAY_WIDTH:-520}"
SHOW_STATUS_OVERLAY_HEIGHT="${SHOW_STATUS_OVERLAY_HEIGHT:-680}"
IMPROVE_AI_LOG_KEEP_LINES=4000
IMPROVE_AI_LOG_TRIM_LINES=8000
POST_REGRESSION_IMPROVE_ENABLED="${POST_REGRESSION_IMPROVE_ENABLED:-1}"
IMPROVE_AUDIO_SUMMARY_ENABLED="${IMPROVE_AUDIO_SUMMARY_ENABLED:-1}"
IMPROVE_AUDIO_SUMMARY_INTERVAL_SEC="${IMPROVE_AUDIO_SUMMARY_INTERVAL_SEC:-900}"
IMPROVE_AUDIO_SUMMARY_STATE_FILE="$TMP_STATE_DIR/improve_audio_summary_last.json"
IMPROVE_AUDIO_SUMMARY_SPEAKER="${IMPROVE_AUDIO_SUMMARY_SPEAKER:-${SOREN91_VOICEVOX_SPEAKER:-46}}"
AUDIO_WORKER_WARNING_INTERVAL_SEC="${AUDIO_WORKER_WARNING_INTERVAL_SEC:-900}"
SOREN_PAUSE_LOG_INTERVAL_SEC="${SOREN_PAUSE_LOG_INTERVAL_SEC:-900}"
COMMENT_CLAUDE_LOG_FILE="$ELOOP_LIB_DIR/$TMP_DEBUG_DIR/comment_claude.log"
IMPROVE_BACKOFF_LOG_INTERVAL_SEC="${IMPROVE_BACKOFF_LOG_INTERVAL_SEC:-900}"
IMPROVE_RUN_CMD_TIMEOUT_SEC="${IMPROVE_RUN_CMD_TIMEOUT_SEC:-1800}"
IMPROVE_FIX_CMD_TIMEOUT_SEC="${IMPROVE_FIX_CMD_TIMEOUT_SEC:-600}"
IMPROVE_OPENCODE_LOCK_MAX_WAIT_SEC="${IMPROVE_OPENCODE_LOCK_MAX_WAIT_SEC:-180}"
IMPROVE_WALL_TIMEOUT="${IMPROVE_WALL_TIMEOUT:-3600}"
IMPROVE_STALE_WATCHDOG_SEC="${IMPROVE_STALE_WATCHDOG_SEC:-600}"
IMPROVE_HUNG_HARVEST_ENABLED="${IMPROVE_HUNG_HARVEST_ENABLED:-1}"
IMPROVE_HUNG_QUARANTINE_FILE="$TMP_STATE_DIR/improve_hung_quarantine.jsonl"
IMPROVE_HUNG_REQUIRE_EVAL_STALE="${IMPROVE_HUNG_REQUIRE_EVAL_STALE:-1}"
EVAL_SCORE_HISTORY_FILE="${EVAL_SCORE_HISTORY_FILE:-eval_score_history.txt}"
SOREN91_IMPROVE_HUNG_HARVEST_ENABLED="${SOREN91_IMPROVE_HUNG_HARVEST_ENABLED:-1}"
SOREN91_IMPROVE_HUNG_SEC="${SOREN91_IMPROVE_HUNG_SEC:-900}"
SOREN91_IMPROVE_HUNG_QUARANTINE_FILE="$TMP_STATE_DIR/soren91_improve_hung_quarantine.jsonl"
POST_IMPROVE_SOREN91_SESSION_IMPROVE_ENABLED="${POST_IMPROVE_SOREN91_SESSION_IMPROVE_ENABLED:-0}"
ACCUMULATED_GAMES_FILE="$TMP_STATE_DIR/accumulated_games.json"
ROLLING_SCORES_FILE="$TMP_STATE_DIR/rolling_scores.json"
CURRENT_STRATEGY_RUN_FILE="$TMP_STATE_DIR/current_strategy_run.json"
REJECTED_HASHES_FILE="$TMP_HISTORY_DIR/rejected_hashes.txt"
REJECTED_HASH_META_FILE="$TMP_STATE_DIR/rejected_hash_metrics.json"
REJECTED_REEVALUATE_TTL_SEC="${REJECTED_REEVALUATE_TTL_SEC:-21600}"
LAST_ROLLBACK_PAIR_FILE="$TMP_STATE_DIR/last_rollback_pair.json"
ROLLBACK_ANALYSIS_FILE="$TMP_STATE_DIR/last_rollback_analysis.md"
ROLLBACK_POSTMORTEM_FILE="$TMP_STATE_DIR/last_rollback_postmortem.md"
ROLLBACK_POSTMORTEM_CONTEXT_FILE="$TMP_STATE_DIR/last_rollback_postmortem_context.md"
ROLLBACK_POSTMORTEM_PID_FILE="$TMP_STATE_DIR/rollback_postmortem.pid"
ROLLBACK_POSTMORTEM_AI_LOG_FILE="$ELOOP_LIB_DIR/$TMP_DEBUG_DIR/rollback_postmortem_ai.log"
BEST_STRATEGY_ANCHOR_FILE="$TMP_STATE_DIR/best_strategy_anchor.json"
ACTIVE_BRANCH_FILE="$TMP_STATE_DIR/active_branch.json"
RUNTIME_RECOVERY_GATE_FILE="$TMP_STATE_DIR/recovery_gate"
REGRESSION_ROLLBACK_DONE=0
REGRESSION_ROLLBACK_HASH=""
MIN_GAMES_BEFORE_IMPROVE="${MIN_GAMES_BEFORE_IMPROVE:-12}"
MIN_GAMES_BEFORE_REGRESSION="${MIN_GAMES_BEFORE_REGRESSION:-12}"
EARLY_OBJECTIVE_REGRESSION_ENABLED="${EARLY_OBJECTIVE_REGRESSION_ENABLED:-1}"
EARLY_OBJECTIVE_REGRESSION_MIN_GAMES="${EARLY_OBJECTIVE_REGRESSION_MIN_GAMES:-4}"
EARLY_OBJECTIVE_REGRESSION_MIN_BEST_TYPE="${EARLY_OBJECTIVE_REGRESSION_MIN_BEST_TYPE:-15}"
RUSSIA_OBJECTIVE_REGRESSION_ENABLED="${RUSSIA_OBJECTIVE_REGRESSION_ENABLED:-1}"
SAME_HASH_BACKSLIDE_RESET_ENABLED="${SAME_HASH_BACKSLIDE_RESET_ENABLED:-1}"
SAME_HASH_BACKSLIDE_MIN_EXTRA_GAMES="${SAME_HASH_BACKSLIDE_MIN_EXTRA_GAMES:-4}"
MIN_GAMES_FOR_BEST_ROLLBACK=12
OBJECTIVE_ANCHOR_PRIORITY_ENABLED="${OBJECTIVE_ANCHOR_PRIORITY_ENABLED:-1}"
OBJECTIVE_ANCHOR_MIN_COMP_RATIO="${OBJECTIVE_ANCHOR_MIN_COMP_RATIO:-0.90}"
OBJECTIVE_ANCHOR_MAX_COMP_GAP="${OBJECTIVE_ANCHOR_MAX_COMP_GAP:-1500}"
REGRESSION_MAX_RANK="${REGRESSION_MAX_RANK:-20}"
RANK_LCB_Z=1.28
RANK_WEIGHT_P50=0.55
RANK_WEIGHT_P25=0.30
RANK_WEIGHT_LCB=0.15
REGRESSION_COMPOSITE_RATIO=0.88
REGRESSION_P50_RATIO=0.85
REGRESSION_P25_RATIO=0.80
REGRESSION_MIN_COMP_GAP="${REGRESSION_MIN_COMP_GAP:-1000}"
REGRESSION_MIN_P50_GAP="${REGRESSION_MIN_P50_GAP:-800}"
REGRESSION_MIN_P25_GAP="${REGRESSION_MIN_P25_GAP:-1600}"
REGRESSION_MIN_BREACH_COUNT=2
BRANCH_MAX_DEPTH="${BRANCH_MAX_DEPTH:-4}"
BRANCH_MAX_GAMES=$((MIN_GAMES_BEFORE_IMPROVE * 4)) # 4サイクル分 (base: 24*4=96)
BRANCH_PATIENCE="${BRANCH_PATIENCE:-3}"
BRANCH_HARD_COMP_GAP="${BRANCH_HARD_COMP_GAP:-2800}"
BRANCH_HARD_P50_GAP="${BRANCH_HARD_P50_GAP:-2200}"
BRANCH_HARD_P25_GAP="${BRANCH_HARD_P25_GAP:-3300}"
BRANCH_HARD_MIN_BREACH_COUNT=2
REGRESSION_TREND_SHORT_WINDOW=50
REGRESSION_TREND_LONG_WINDOW=100
REGRESSION_TREND_SHORT_RATIO=0.94
REGRESSION_TREND_LONG_RATIO=0.95

# --- 帯域脱出機構 (D+E+F) ---
# D: 多様性プレミアム (anchor 選定時のメモリ内 selection_score のみに作用、永続化しない)
DIVERSITY_PREMIUM_ENABLED="${DIVERSITY_PREMIUM_ENABLED:-0}"
DIVERSITY_PREMIUM_WEIGHT="${DIVERSITY_PREMIUM_WEIGHT:-300}"
EXPLORE_GAP_MAX_RATIO="${EXPLORE_GAP_MAX_RATIO:-0.07}"
# E: 機械的 tabu (rollback された失敗 current の挙動近傍を一定期間 anchor 昇格不可に)
TABU_ENABLED="${TABU_ENABLED:-0}"
TABU_DISTANCE_THRESHOLD="${TABU_DISTANCE_THRESHOLD:-0.15}"
TABU_RETAIN="${TABU_RETAIN:-20}"
TABU_DECAY_GAMES="${TABU_DECAY_GAMES:-$((MIN_GAMES_BEFORE_IMPROVE * 8))}"
TABU_SIGNATURES_FILE="${TABU_SIGNATURES_FILE:-$TMP_STATE_DIR/tabu_signatures.jsonl}"
BEHAVIOR_SIGNATURES_FILE="${BEHAVIOR_SIGNATURES_FILE:-$TMP_STATE_DIR/behavior_signatures.json}"
HASH_HISTORY_INDEX_FILE="$TMP_STATE_DIR/hash_history_index.json"
LAST_ANCHOR_CHANGE_FILE="${LAST_ANCHOR_CHANGE_FILE:-$TMP_STATE_DIR/last_anchor_change.md}"
# F: wildcard パラメータ摂動 (連続 N サイクル無改善で AI を介さず数値定数を ±σ 摂動)
WILDCARD_ENABLED="${WILDCARD_ENABLED:-0}"
WILDCARD_TRIGGER_STAGNATION="${WILDCARD_TRIGGER_STAGNATION:-3}"
WILDCARD_EARLY_ESCAPE_LOCK_ENABLED="${WILDCARD_EARLY_ESCAPE_LOCK_ENABLED:-1}"
WILDCARD_EARLY_ESCAPE_MIN_GAMES="${WILDCARD_EARLY_ESCAPE_MIN_GAMES:-4}"
# counter 非依存トリガ: 回帰ストリークが閾値到達で WILDCARD 発火 (OK_BEAT マスク回避)。
# churn 緩和: rstreak 経路の連続発火を COOLDOWN 秒抑止 (cooldown マーカは improve.sh 所有)。
WILDCARD_REGRESSION_STREAK="${WILDCARD_REGRESSION_STREAK:-2}"
WILDCARD_STREAK_COOLDOWN_SEC="${WILDCARD_STREAK_COOLDOWN_SEC:-1800}"
WILDCARD_STREAK_COOLDOWN_FILE="$TMP_STATE_DIR/.wildcard_streak_cooldown"
WILDCARD_PARAM_COUNT_MIN="${WILDCARD_PARAM_COUNT_MIN:-1}"
WILDCARD_PARAM_COUNT_MAX="${WILDCARD_PARAM_COUNT_MAX:-3}"
WILDCARD_PERTURB_RATIO_MIN="${WILDCARD_PERTURB_RATIO_MIN:-0.20}"
WILDCARD_PERTURB_RATIO_MAX="${WILDCARD_PERTURB_RATIO_MAX:-0.40}"
WILDCARD_ADAPTIVE_SCALE_ENABLED="${WILDCARD_ADAPTIVE_SCALE_ENABLED:-1}"
WILDCARD_ADAPTIVE_SCALE_STEP="${WILDCARD_ADAPTIVE_SCALE_STEP:-0.25}"
WILDCARD_ADAPTIVE_SCALE_MAX="${WILDCARD_ADAPTIVE_SCALE_MAX:-2.00}"
WILDCARD_ADAPTIVE_EXTRA_PARAM_EVERY="${WILDCARD_ADAPTIVE_EXTRA_PARAM_EVERY:-2}"
WILDCARD_TABU_RECENT_LINES="${WILDCARD_TABU_RECENT_LINES:-12}"
WILDCARD_AI_ESCALATE_ENABLED="${WILDCARD_AI_ESCALATE_ENABLED:-1}"
WILDCARD_AI_ESCALATE_STREAK="${WILDCARD_AI_ESCALATE_STREAK:-3}"
WILDCARD_ESCAPE_AI_SEED_ENABLED="${WILDCARD_ESCAPE_AI_SEED_ENABLED:-1}"
WILDCARD_ESCAPE_AI_SEED_MIN_GAMES="${WILDCARD_ESCAPE_AI_SEED_MIN_GAMES:-4}"
WILDCARD_BANDIT_ENABLED="${WILDCARD_BANDIT_ENABLED:-1}"
WILDCARD_BANDIT_LOOKBACK="${WILDCARD_BANDIT_LOOKBACK:-80}"
WILDCARD_BANDIT_EXPLORE_RATE="${WILDCARD_BANDIT_EXPLORE_RATE:-0.35}"
WILDCARD_PATIENCE_GAMES="${WILDCARD_PATIENCE_GAMES:-12}"
ARCHIVE_RESTART_ENABLED="${ARCHIVE_RESTART_ENABLED:-1}"
ARCHIVE_RESTART_STREAK="${ARCHIVE_RESTART_STREAK:-3}"
ARCHIVE_RESTART_MIN_COMP_RATIO="${ARCHIVE_RESTART_MIN_COMP_RATIO:-0.92}"
ARCHIVE_RESTART_MIN_BEST_TYPE="${ARCHIVE_RESTART_MIN_BEST_TYPE:-14}"
ARCHIVE_RESTART_MAX_CANDIDATES="${ARCHIVE_RESTART_MAX_CANDIDATES:-24}"
ARCHIVE_RESTART_PATIENCE_GAMES="${ARCHIVE_RESTART_PATIENCE_GAMES:-12}"
ARCHIVE_RESTART_COOLDOWN_FILE="$TMP_STATE_DIR/archive_restart_cooldown.json"
ARCHIVE_RESTART_NO_CANDIDATE_COOLDOWN_FILE="$TMP_STATE_DIR/.archive_restart_no_candidate"
ARCHIVE_RESTART_NO_CANDIDATE_COOLDOWN_SEC="${ARCHIVE_RESTART_NO_CANDIDATE_COOLDOWN_SEC:-900}"
ANNEALING_OBSERVE_ENABLED="${ANNEALING_OBSERVE_ENABLED:-1}"
ANNEALING_BASE_TEMP="${ANNEALING_BASE_TEMP:-1800}"
ANNEALING_DECAY="${ANNEALING_DECAY:-0.85}"
STAGNATION_COUNTER_FILE="$TMP_STATE_DIR/stagnation_counter.json"
WILDCARD_ORIGIN_FILE="$TMP_STATE_DIR/wildcard_origin.json"
WILDCARD_ATTEMPT_STATE_FILE="$TMP_STATE_DIR/wildcard_attempt_state.json"
WILDCARD_OUTCOME_FILE="$TMP_STATE_DIR/wildcard_outcomes.jsonl"
ANNEALING_OBSERVE_FILE="$TMP_STATE_DIR/annealing_candidates.jsonl"
WILDCARD_PROGRESS_AUDIO_ENABLED="${WILDCARD_PROGRESS_AUDIO_ENABLED:-1}"
WILDCARD_PROGRESS_AUDIO_STATE_FILE="$TMP_STATE_DIR/wildcard_progress_audio_last.json"
WILDCARD_PROGRESS_AUDIO_MILESTONES="${WILDCARD_PROGRESS_AUDIO_MILESTONES:-1,3,6,9,12}"
WILDCARD_PROGRESS_AUDIO_MIN_DELTA="${WILDCARD_PROGRESS_AUDIO_MIN_DELTA:-0}"
MONITOR_REPORT_AUDIO_ENABLED="${MONITOR_REPORT_AUDIO_ENABLED:-1}"
MONITOR_REPORT_AUDIO_STATE_FILE="$TMP_STATE_DIR/monitor_report_audio_last.json"
MONITOR_REPORT_STATUS_FILE="${MONITOR_REPORT_STATUS_FILE:-$TMP_STATE_DIR/monitor_report_status.json}"
MONITOR_REPORT_STALE_SEC="${MONITOR_REPORT_STALE_SEC:-900}"
MONITOR_REPORT_OLD_SEC="${MONITOR_REPORT_OLD_SEC:-3600}"
MONITOR_REPORT_AUDIO_MIN_INTERVAL_SEC="${MONITOR_REPORT_AUDIO_MIN_INTERVAL_SEC:-900}"
MONITOR_REPORT_IMPROVE_GUARD_ENABLED="${MONITOR_REPORT_IMPROVE_GUARD_ENABLED:-0}"
MONITOR_REPORT_IMPROVE_GUARD_MAX_AGE="${MONITOR_REPORT_IMPROVE_GUARD_MAX_AGE:-3600}"
VIEWER_CHAT_MONITOR_FILE="${VIEWER_CHAT_MONITOR_FILE:-$ELOOP_LIB_DIR/$TMP_STATE_DIR/viewer_chat_monitor.json}"
VIEWER_CHAT_MONITOR_SOURCE="${VIEWER_CHAT_MONITOR_SOURCE:-$ELOOP_LIB_DIR/tmp/.twitch_chat/comment_context_history.log}"
VIEWER_CHAT_MONITOR_LOOKBACK="${VIEWER_CHAT_MONITOR_LOOKBACK:-200}"
CURRENT_RUN_AUTO_REPAIR_ENABLED="${CURRENT_RUN_AUTO_REPAIR_ENABLED:-1}"
CURRENT_RUN_AUTO_REPAIR_LIMIT="${CURRENT_RUN_AUTO_REPAIR_LIMIT:-12}"

# Dashboard OBS visibility 制御
# プレイ中は dashboard ソースを hide、GAMEOVER 時に show する。meriken AI と同じパターン
OBS_DASHBOARD_VISIBILITY_ENABLED="${OBS_DASHBOARD_VISIBILITY_ENABLED:-1}"
OBS_DASHBOARD_SCENE="${OBS_DASHBOARD_SCENE:-soren}"
OBS_DASHBOARD_SOURCE="${OBS_DASHBOARD_SOURCE:-dashboard}"
DASHBOARD_GAMEOVER_HOLD_SEC="${DASHBOARD_GAMEOVER_HOLD_SEC:-3}"

STRATEGY_HASH_ARCHIVE_DIR="strategy_versions/by_hash"
# 永続アーカイブ: prune されないバックアップ。backfill のフォールバック元
STRATEGY_HASH_PERMANENT_ARCHIVE_DIR="strategy_versions_archive/by_hash"
# 旧設定の keep_top=10 が親シェルに残っていても、既定値は 100 に引き上げる。
case "${HASH_ARCHIVE_KEEP_TOP:-}" in
"" | 10) HASH_ARCHIVE_KEEP_TOP=100 ;;
esac
case "${HASH_ARCHIVE_PRUNE_SAFETY_MIN_KEEP:-}" in
"" | *[!0-9]*) HASH_ARCHIVE_PRUNE_SAFETY_MIN_KEEP=20 ;;
esac
[ "$HASH_ARCHIVE_PRUNE_SAFETY_MIN_KEEP" -lt 1 ] && HASH_ARCHIVE_PRUNE_SAFETY_MIN_KEEP=1
case "${HASH_ARCHIVE_PRUNE_SAFETY_MIN_RATIO_PCT:-}" in
"" | *[!0-9]*) HASH_ARCHIVE_PRUNE_SAFETY_MIN_RATIO_PCT=60 ;;
esac
[ "$HASH_ARCHIVE_PRUNE_SAFETY_MIN_RATIO_PCT" -lt 1 ] && HASH_ARCHIVE_PRUNE_SAFETY_MIN_RATIO_PCT=1
[ "$HASH_ARCHIVE_PRUNE_SAFETY_MIN_RATIO_PCT" -gt 100 ] && HASH_ARCHIVE_PRUNE_SAFETY_MIN_RATIO_PCT=100
HASH_ARCHIVE_RESTORE_PERMANENT="${HASH_ARCHIVE_RESTORE_PERMANENT:-0}"
HASH_ARCHIVE_PRUNE_BACKGROUND="${HASH_ARCHIVE_PRUNE_BACKGROUND:-1}"
COMMENT_QUEUE_DIR="tmp/.comment_queue"
COMMENT_SPOKEN_HISTORY_DIR="tmp/.comment_queue/spoken_history"
COMMENT_SPOKEN_HISTORY_MAX_FILES="${COMMENT_SPOKEN_HISTORY_MAX_FILES:-16}"
COMMENT_SPOKEN_PROMPT_ITEMS="${COMMENT_SPOKEN_PROMPT_ITEMS:-20}"
COMMENT_SPOKEN_PROMPT_MAX_CHARS="${COMMENT_SPOKEN_PROMPT_MAX_CHARS:-8000}"
COMMENT_SPOKEN_ITEM_MAX_CHARS="${COMMENT_SPOKEN_ITEM_MAX_CHARS:-700}"
RUSSIA_CELEBRATION_WORKER_PID_FILE="$TMP_STATE_DIR/.russia_celebration_worker.pid"
COMMENT_WATCHER_PID_FILE="tmp/.comment_queue/watcher.pid"
COMMENT_WATCHER_INTERVAL=10
COMMENT_WORKER_HEALTH_TTL=30
COMMENT_PLAYER_HEARTBEAT_FILE="tmp/.comment_queue/player.heartbeat"
COMMENT_WATCHER_HEARTBEAT_FILE="tmp/.comment_queue/watcher.heartbeat"
COMMENT_BATCH_HISTORY_FILE="tmp/.comment_queue/processed_batch_hashes.log"
COMMENT_BATCH_INFLIGHT_FILE="tmp/.comment_queue/inflight_batch.log"
COMMENT_BATCH_DEDUP_TTL=900
COMMENT_PROCESSED_LINES_FILE="tmp/.comment_queue/processed_line_hashes.log"
COMMENT_PROCESSED_LINES_TTL=1800
COMMENT_PROCESSED_LINES_MAX=500
SOREN91_LAST_COMMENTED_GAME_FILE="$COMMENT_QUEUE_DIR/soren91_last_commented_game"
SOREN91_GAME_COMMENTARY_INTERVAL=60
RADIO_DEFERRED_QUEUE_DIR="tmp/.radio_deferred_queue"
OUTBOUND_CHAT_QUEUE_DIR="tmp/.outbound_chat_queue"
OUTBOUND_CHAT_PENDING_DIR="$OUTBOUND_CHAT_QUEUE_DIR/pending"
OUTBOUND_CHAT_SENT_DIR="$OUTBOUND_CHAT_QUEUE_DIR/sent"
MANUAL_AUDIO_TRIGGER_DIR="tmp/.manual_audio_triggers"
MANUAL_AUDIO_TRIGGER_MAX_PER_TICK=3
RUSSIA_CELEBRATION_CLIP_DELAY_SEC="${RUSSIA_CELEBRATION_CLIP_DELAY_SEC:-5}"
SOVIET_CELEBRATION_CLIP_DELAY_SEC="${SOVIET_CELEBRATION_CLIP_DELAY_SEC:-20}"
mkdir -p "$STRATEGY_VERSIONS_DIR" "$STRATEGY_HASH_ARCHIVE_DIR" "$STRATEGY_HASH_PERMANENT_ARCHIVE_DIR" "$HISTORY_DIR" \
	"$TMP_STATE_DIR" "$TMP_MARKERS_DIR" "$TMP_HISTORY_DIR" "$TMP_DEBUG_DIR" "$TMP_CACHE_DIR" \
	"$COMMENT_QUEUE_DIR" "$COMMENT_SPOKEN_HISTORY_DIR" "$RADIO_DEFERRED_QUEUE_DIR" \
	"$MANUAL_AUDIO_TRIGGER_DIR" "$RADIO_WEB_GROUNDING_CACHE_DIR" \
	"$OUTBOUND_CHAT_PENDING_DIR" "$OUTBOUND_CHAT_SENT_DIR" \
	"tmp/.twitch_chat"

if [ -f "tmp/advice.md" ] && [ ! -f "$MAIN_STRATEGY_ADVICE_FILE" ]; then
	mv "tmp/advice.md" "$MAIN_STRATEGY_ADVICE_FILE" 2>/dev/null || cp "tmp/advice.md" "$MAIN_STRATEGY_ADVICE_FILE" 2>/dev/null || true
fi

# --- tmp/ レイアウト移行 (旧パス → 新サブディレクトリ) ---
if [ ! -f "$TMP_STATE_DIR/.migrated" ]; then
	# state files
	for f in improve_state.json accumulated_games.json rolling_scores.json \
		rejected_hash_metrics.json best_strategy_anchor.json active_branch.json last_rollback_pair.json .russia_celebration_worker.pid \
		.radio_state .comment_gen_state radio_talk_played .news_last_success.txt \
		.status_fullscreen_last .news_shown_lines.txt .news_shown_mtime.txt; do
		[ -f "tmp/$f" ] && mv "tmp/$f" "$TMP_STATE_DIR/$f" 2>/dev/null
	done
	# markers
	for f in tmp/.radio_done_* tmp/.radio_inflight_* tmp/.timed_corner_done_* tmp/.timed_corner_inflight_*; do
		[ -e "$f" ] && mv "$f" "$TMP_MARKERS_DIR/" 2>/dev/null
	done
	for f in .russia_created .soviet_created; do
		[ -f "tmp/$f" ] && mv "tmp/$f" "$TMP_MARKERS_DIR/$f" 2>/dev/null
	done
	# history
	for f in .past_radio_themes.txt past_radio_topics.txt past_news_read.txt \
		past_radio_theme_bodies.txt past_news_read_keys.txt past_news_topic_keys.txt past_news_read_sources.txt rejected_hashes.txt \
		.past_news_titles.txt .past_news_links.txt russia_creation_history.tsv soviet_creation_history.tsv; do
		[ -f "tmp/$f" ] && mv "tmp/$f" "$TMP_HISTORY_DIR/$f" 2>/dev/null
	done
	# debug
	for f in tmp/radio_short_*.txt tmp/radio_factcheck_failed_*.txt tmp/radio_russia_celebration.txt; do
		[ -e "$f" ] && mv "$f" "$TMP_DEBUG_DIR/" 2>/dev/null
	done
	[ -f "tmp/improve_ai.log" ] && mv "tmp/improve_ai.log" "$TMP_DEBUG_DIR/improve_ai.log" 2>/dev/null
	touch "$TMP_STATE_DIR/.migrated"
fi
