# core/config.sh - 全定数・パス定義・mkdir初期化
#
# ELOOP_LIB_DIR は eloop_lib.sh (shim) で設定済み。
# このファイルでは再設定しない。

# --- モード切替 ---
# EXPLORE_MODE=1: 探索モード（配信なし）。実ゲームで戦略改善ループのみ回す。
# ・.benv/.env に書かない（explore.sh が export + tmp/state/explore_mode マーカで固定）
# ・runtime_toggles.sh のホワイトリストに含めない（実行中 hot-toggle 不可）
EXPLORE_MODE="${EXPLORE_MODE:-0}"
STREAMING_ENABLED="${STREAMING_ENABLED:-$((1 - EXPLORE_MODE))}"

# --- 定数 ---
COMMANDS="commands.txt"
GAME_STATE="game_state.json"

STRATEGY_FILE="strategy.py"
STRATEGY_VERSIONS_DIR="strategy_versions"
HISTORY_DIR="game_history"
HISTORY_FILE="$HISTORY_DIR/latest.jsonl"
PHYROGENETIC_TREE_FILE="phyrogenetic-tree.md"
PHYROGENETIC_EVENTS_FILE="phyrogenetic-events.jsonl"
PHYROGENETIC_TREE_URL="${PHYROGENETIC_TREE_URL:-https://github.com/azumag/soviet_now/blob/main/phyrogenetic-tree.md}"

MODEL_IMPROVE="${MODEL_IMPROVE:-opencode:x-preview-f-free}"
REGRESSION_DISABLED=0
MERIKEN_SCHEDULED_TIME_ENABLED=0 # 旧20-21時メリケンAIタイムを無効化
SOREN91_DAILY_ENABLED="${SOREN91_DAILY_ENABLED:-0}"
SOREN91_DAILY_EARLIEST_HOUR="${SOREN91_DAILY_EARLIEST_HOUR:-8}"
SOREN91_DAILY_LATEST_START_HOUR="${SOREN91_DAILY_LATEST_START_HOUR:-22}"
SOREN91_DAILY_DURATION_SEC="${SOREN91_DAILY_DURATION_SEC:-3600}"
SOREN91_DAILY_MAX_ATTEMPTS="${SOREN91_DAILY_MAX_ATTEMPTS:-3}"
SOREN91_DAILY_RETRY_SEC="${SOREN91_DAILY_RETRY_SEC:-600}"
SOREN91_DAILY_READY_TIMEOUT_SEC="${SOREN91_DAILY_READY_TIMEOUT_SEC:-120}"
SOREN91_DAILY_TIMEZONE="${SOREN91_DAILY_TIMEZONE:-Asia/Tokyo}"
SOREN91_VIEWPORT_WIDTH="${SOREN91_VIEWPORT_WIDTH:-480}"
SOREN91_VIEWPORT_HEIGHT="${SOREN91_VIEWPORT_HEIGHT:-270}"
SOREN91_FULLSCREEN_WINDOW="${SOREN91_FULLSCREEN_WINDOW:-1}"
SOREN91_NORMAL_GAME_CPU_THROTTLE="${SOREN91_NORMAL_GAME_CPU_THROTTLE:-8}"
SOREN91_AUDIO_RESUME_GRACE_SEC="${SOREN91_AUDIO_RESUME_GRACE_SEC:-15}"
MODEL_FALLBACK_IMPROVE="${MODEL_FALLBACK_IMPROVE:-opencode-go:muse-spark-1.2-contributor}"
MODEL_LAST_RESORT="codex:deepseek-v4-flash"
# ===== 共通モデルチェーン =====
# 全 AI 生成系の単一の順序原典。低コスト/無料枠を先頭、有償枠を末尾に置く。
# 有償枠内は muse-spark contributor を DeepSeek 系より先に使う。
# 各用途はこのリストを基底に、local を含めるか・特定枠を外すかだけを変える。
# deepseek-v4-flash-free は opencode 直呼びで成功する（litellm の zen/v1 は 429）。opencode: で呼ぶ.
# muse-spark-1.2-contributor は opencode-go 経由（要 opt-in https://opencode.ai/workspace/wrk_01M04NATCGAVB03SVAEZ4RBV1Y/go）で提供。
# provider は opencode-go のため prefix は opencode-go:（opencode: だと zen 側の free 枠と衝突し Model not found になる）。
AI_COMMON_AGENTS="${AI_COMMON_AGENTS:-opencode:x-preview-f-free,codex:amd-token-factory-deepseek-v4-flash,codex:minimax-m3,opencode-go:muse-spark-1.2-contributor,codex:deepseek-v4-flash}"

# MODEL_IMPROVE_LIST: 改善ループのリスト。共通チェーンから local と openrouter/free を
# 除いたもの。run_ai_list() が順に試行する。
MODEL_IMPROVE_LIST="${MODEL_IMPROVE_LIST:-opencode:x-preview-f-free,codex:amd-token-factory-deepseek-v4-flash,codex:minimax-m3,opencode-go:muse-spark-1.2-contributor,codex:deepseek-v4-flash}"
# ピーク時間帯用の改善チェーン。空なら MODEL_IMPROVE_LIST を継承。
MODEL_IMPROVE_PEAK_LIST="${MODEL_IMPROVE_PEAK_LIST:-}"
# ピークチェーンを有効化するか。0=常に MODEL_IMPROVE_LIST、1=ピーク時は PEAK_LIST を使用。
IMPROVE_PEAK_CHAIN_ENABLED="${IMPROVE_PEAK_CHAIN_ENABLED:-0}"

GAME_COUNT_FILE="game_count.txt"

RADIO_MAIN_AGENT="${RADIO_MAIN_AGENT:-opencode:x-preview-f-free}"
RADIO_MAIN_PREPASS_AGENT="${RADIO_MAIN_PREPASS_AGENT:-opencode:x-preview-f-free}"
RADIO_MAIN_FALLBACK="${RADIO_MAIN_FALLBACK:-codex:amd-token-factory-deepseek-v4-flash}"
# RADIO_AGENTS: ラジオ生成エージェントのフォールバックリスト（カンマ区切り、優先度順）
# ai_generate_list() がバックオフ付きで順に試行する
RADIO_AGENTS="${RADIO_AGENTS:-$AI_COMMON_AGENTS}"
# RADIO_PREPASS_AGENTS: 事前調査 (prepass) のモデルフォールバックリスト。共通チェーンを
# そのまま使う。ai_generate_list() が順に試行する。
RADIO_PREPASS_AGENTS="${RADIO_PREPASS_AGENTS:-$AI_COMMON_AGENTS}"
AI_AGENT_BACKOFF_SEC="${AI_AGENT_BACKOFF_SEC:-600}"
RADIO_OPENCODE_DEFER_DURING_IMPROVE="${RADIO_OPENCODE_DEFER_DURING_IMPROVE:-1}"
# AIレーン同時実行制御 (issue #7 必須条件)。放送系 (RADIO/NEWS/JIJI/CELEBRATION) は
# モデル差に関係なく単一ロックへ直列化、コメント返しも comment レーンで直列化する。
# 全体で 放送系1 + コメント返し1 + 改善1 の最大3並列になる。
# 改善ジョブ稼働中は新規の放送系生成のみ待機する (開始済み生成はキャンセルしない)。
# 読み上げ/TTSはAI呼出を経ないため影響を受けない。
AI_RADIO_LANE_LOCK="${AI_RADIO_LANE_LOCK:-1}"
AI_COMMENT_LANE_LOCK="${AI_COMMENT_LANE_LOCK:-1}"
AI_RADIO_IMPROVE_GATE="${AI_RADIO_IMPROVE_GATE:-1}"
# 改善中に放送系生成が待機する上限秒。超過したらその生成だけ諦める
# (改善サイクル実測 439-828秒のため余裕を見て1200秒)。
AI_RADIO_IMPROVE_WAIT_MAX_SEC="${AI_RADIO_IMPROVE_WAIT_MAX_SEC:-1200}"
RADIO_OPENCODE_TIMEOUT=180
# JIJIはWeb検索を含む長めの調査で、共有radioレーン待ちと重なりやすい。
RADIO_JIJI_RESEARCH_TIMEOUT="${RADIO_JIJI_RESEARCH_TIMEOUT:-300}"
OLLAMA_BASE_URL="${OLLAMA_BASE_URL:-http://192.168.11.13:11434}"
LOCAL_LLM_BASE_URL="${LOCAL_LLM_BASE_URL:-http://100.112.104.102:11434}"
LOCAL_LLM_MODEL="${LOCAL_LLM_MODEL:-gemma4:12b}"
LOCAL_LLM_TIMEOUT="${LOCAL_LLM_TIMEOUT:-180}"
LOCAL_LLM_AGENTS="${LOCAL_LLM_AGENTS:-qwen35e qwen3.5:9b gemma4nt ccogent gemma4nt_ccogent}"
RADIO_OLLAMA_MODEL="${RADIO_OLLAMA_MODEL:-qwen3.5:9b}"
RADIO_OLLAMA_TIMEOUT="${RADIO_OLLAMA_TIMEOUT:-300}"
COMMENT_OLLAMA_MODEL="${COMMENT_OLLAMA_MODEL:-qwen3.5:9b}"
COMMENT_OLLAMA_MODEL_IMPROVING="${COMMENT_OLLAMA_MODEL_IMPROVING:-gemma4:latest}"
COMMENT_OLLAMA_TIMEOUT="${COMMENT_OLLAMA_TIMEOUT:-20}"
COMMENT_CLASSIFIER_AGENT="${COMMENT_CLASSIFIER_AGENT:-opencode:x-preview-f-free}"
COMMENT_CLASSIFIER_FALLBACK="${COMMENT_CLASSIFIER_FALLBACK:-codex:amd-token-factory-deepseek-v4-flash}"
COMMENT_CLASSIFIER_EDIT_AGENT="${COMMENT_CLASSIFIER_EDIT_AGENT:-opencode:x-preview-f-free}"
COMMENT_CLASSIFIER_EDIT_FALLBACK="${COMMENT_CLASSIFIER_EDIT_FALLBACK:-codex:amd-token-factory-deepseek-v4-flash}"
COMMENT_CLASSIFIER_EDIT_TIMEOUT="${COMMENT_CLASSIFIER_EDIT_TIMEOUT:-45}"
COMMENT_CLASSIFIER_TIMEOUT="${COMMENT_CLASSIFIER_TIMEOUT:-90}"
COMMENT_CLASSIFIER_AI_ENABLED="${COMMENT_CLASSIFIER_AI_ENABLED:-0}"
COMMENT_CLASSIFIER_OPENCODE_PERMISSION_DEFAULT='{"*":"deny","read":"allow","glob":"allow","grep":"allow","list":"allow","edit":"allow","write":"allow","external_directory":"allow"}'
COMMENT_CLASSIFIER_OPENCODE_PERMISSION="${COMMENT_CLASSIFIER_OPENCODE_PERMISSION:-$COMMENT_CLASSIFIER_OPENCODE_PERMISSION_DEFAULT}"
CODEX_BUG_DISPATCH_ENABLED="${CODEX_BUG_DISPATCH_ENABLED:-1}"
CODEX_BUG_DISPATCH_MIN_INTERVAL_SEC="${CODEX_BUG_DISPATCH_MIN_INTERVAL_SEC:-900}"
CODEX_BUG_DISPATCH_CODEX_CMD="${CODEX_BUG_DISPATCH_CODEX_CMD:-codex}"
CODEX_BUG_DISPATCH_MODEL="${CODEX_BUG_DISPATCH_MODEL:-}"
# COMMENT_AGENTS: コメント返し生成エージェントのフォールバックリスト（カンマ区切り、優先度順）
# 共通チェーン（AI_COMMON_AGENTS）を基底に使う。ai_generate_list() が順に試行する。
COMMENT_AGENTS="${COMMENT_AGENTS:-$AI_COMMON_AGENTS}"
COMMENT_TRANSLATION_AGENTS="${COMMENT_TRANSLATION_AGENTS:-$COMMENT_AGENTS}"
COMMENT_TRANSLATION_TIMEOUT="${COMMENT_TRANSLATION_TIMEOUT:-60}"
# --- Twitch 自動アンケートコーナー (docich#8) ---
# broadcaster の channel:manage:polls 付き user token が必要。既存の予想用
# token に同 scope が含まれる場合は TWITCH_PREDICTIONS_TOKEN を再利用できる。
TWITCH_POLLS_ENABLED="${TWITCH_POLLS_ENABLED:-0}"
TWITCH_POLLS_TOKEN="${TWITCH_POLLS_TOKEN:-${TWITCH_PREDICTIONS_TOKEN:-}}"
TWITCH_POLL_INTERVAL_SEC="${TWITCH_POLL_INTERVAL_SEC:-600}"
TWITCH_POLL_INITIAL_DELAY_SEC="${TWITCH_POLL_INITIAL_DELAY_SEC:-600}"
TWITCH_POLL_DURATION_SEC="${TWITCH_POLL_DURATION_SEC:-120}"
TWITCH_POLL_WORKER_INTERVAL="${TWITCH_POLL_WORKER_INTERVAL:-10}"
TWITCH_POLL_RETRY_SEC="${TWITCH_POLL_RETRY_SEC:-600}"
TWITCH_POLL_AGENTS="${TWITCH_POLL_AGENTS:-$RADIO_AGENTS}"
TWITCH_POLL_AI_TIMEOUT="${TWITCH_POLL_AI_TIMEOUT:-120}"
# --- YouTube ライブ枠の自動復旧 ---
# OAuth は youtube.force-ssl または youtube scope が必要。既定は完全無効で、
# 有効化しても AUTO_CREATE=1 までは監視だけ。映像キーやtokenはstate/logへ書かない。
YOUTUBE_BROADCAST_GUARD_ENABLED="${YOUTUBE_BROADCAST_GUARD_ENABLED:-0}"
YOUTUBE_BROADCAST_GUARD_AUTO_CREATE="${YOUTUBE_BROADCAST_GUARD_AUTO_CREATE:-0}"
YOUTUBE_BROADCAST_GUARD_RESTART_PUBLISHER="${YOUTUBE_BROADCAST_GUARD_RESTART_PUBLISHER:-1}"
YOUTUBE_BROADCAST_GUARD_POLL_SEC="${YOUTUBE_BROADCAST_GUARD_POLL_SEC:-60}"
YOUTUBE_BROADCAST_GUARD_MISSING_CONFIRMATIONS="${YOUTUBE_BROADCAST_GUARD_MISSING_CONFIRMATIONS:-3}"
YOUTUBE_BROADCAST_GUARD_CREATE_COOLDOWN_SEC="${YOUTUBE_BROADCAST_GUARD_CREATE_COOLDOWN_SEC:-900}"
YOUTUBE_BROADCAST_GUARD_LIVE_TIMEOUT_SEC="${YOUTUBE_BROADCAST_GUARD_LIVE_TIMEOUT_SEC:-120}"
YOUTUBE_BROADCAST_GUARD_PRIVACY="${YOUTUBE_BROADCAST_GUARD_PRIVACY:-public}"
YOUTUBE_BROADCAST_GUARD_TITLE="${YOUTUBE_BROADCAST_GUARD_TITLE:-中華AIと メリケンAIによる自動ソ連建国チャレンジ [ソ連ゲーム]}"
YOUTUBE_BROADCAST_GUARD_STATE_FILE="${YOUTUBE_BROADCAST_GUARD_STATE_FILE:-tmp/state/youtube_broadcast_guard.json}"
YOUTUBE_BROADCAST_GUARD_PID_FILE="${YOUTUBE_BROADCAST_GUARD_PID_FILE:-tmp/state/youtube_broadcast_guard.pid}"
COMMENT_SOREN91_AGENT="${COMMENT_SOREN91_AGENT:-opencode:x-preview-f-free}"
COMMENT_SOREN91_FALLBACK="${COMMENT_SOREN91_FALLBACK:-codex:amd-token-factory-deepseek-v4-flash}"
RADIO_SOREN91_AGENT="${RADIO_SOREN91_AGENT:-opencode:x-preview-f-free}"
RADIO_SOREN91_FALLBACK="${RADIO_SOREN91_FALLBACK:-codex:amd-token-factory-deepseek-v4-flash}"
# --- ピーク時間帯のエージェント優先順位入替え ---
# ピーク時は RADIO_AGENTS / COMMENT_AGENTS の「候補順序」だけを入替え、
# PEAK_HOURS_PRIORITY_AGENT を先頭へ寄せる。候補の削除はしない（DeepSeek はフォールバックに残る）。
PEAK_HOURS_AGENT_SWAP_ENABLED="${PEAK_HOURS_AGENT_SWAP_ENABLED:-1}"
# "開始-終了" をカンマ区切りで複数指定。開始は含み、終了は含まない。
# 各端点は HH / HHMM / HH:MM 形式。開始>終了なら日跨ぎ (例 22-02) として扱う。
# 明示的に空文字にするとウィンドウなし＝常に非ピーク扱い（`-` 展開なので unset 時のみ既定値を使う）。
# 切替機能自体を止めたいだけなら PEAK_HOURS_AGENT_SWAP_ENABLED=0 を使う。
PEAK_HOURS_WINDOWS="${PEAK_HOURS_WINDOWS-10-13,15-19}"
PEAK_HOURS_TZ="${PEAK_HOURS_TZ:-Asia/Tokyo}"
PEAK_HOURS_PRIORITY_AGENT="${PEAK_HOURS_PRIORITY_AGENT:-opencode:x-preview-f-free}"
# ピーク時の優先順序（先頭ほど優先）。最上位から該当する候補へ並べ直す。
# x-preview > muse > MiniMax > 残り（DeepSeek系）。
PEAK_HOURS_AGENT_PREFERENCE="${PEAK_HOURS_AGENT_PREFERENCE:-opencode:x-preview-f-free,codex:amd-token-factory-deepseek-v4-flash,codex:minimax-m3,opencode-go:muse-spark-1.2-contributor}"

# ===== モデル別バックオフ時間（秒） =====
# ai_generate_list がエージェント単位で失敗時に用いる。キーは agent から
# `codex:` プレフィックスを除いたモデル名相当（local はそのまま）。
# 既定（該当なし）は AI_AGENT_BACKOFF_SEC。muse-spark-1.2-contributor は opencode-go 契約の
# クォータ制枠のため 1 日バックオフ。
AI_BACKOFF_SEC_ITEMS="deepseek-v4-flash-free:86400 amd-token-factory-deepseek-v4-flash:86400 openrouter/free:86400 local:1800 deepseek-v4-flash:18000 minimax-m3:18000 muse-spark-1.2-contributor:86400"
# レート制限/クォータ以外の失敗（プロバイダダウン・認証・一時的な CLI 障害）に使う
# 短いバックオフ。1日級のパークは Q数枯渇（429）に限定し、一過性の失敗では
# 無料枠を早期に復帰させる。
AI_BACKOFF_FAILURE_SEC="${AI_BACKOFF_FAILURE_SEC:-300}"
# ピーク時間帯限定: issue #5 のバックプレッシャー(MAX=5)とは別に、ピーク中はキューが
# 完全に空(0件)になるまで新規ラジオ生成をブロックする追加ゲート。同一tick内で複数
# コーナーの時刻窓が重なった場合、ゲート開放時にまとめて生成されることがある。
# ピーク外はこのゲート自体が無効（常に issue #5 の MAX=5 のみが効く）。
PEAK_HOURS_QUEUE_GATE_ENABLED="${PEAK_HOURS_QUEUE_GATE_ENABLED:-1}"
COMMENT_GENERATION_HISTORY_FILE="${TMP_HISTORY_DIR:-tmp/history}/comment_generation_history.jsonl"
RADIO_GENERATION_HISTORY_FILE="${TMP_HISTORY_DIR:-tmp/history}/radio_generation_history.jsonl"
COMMENT_GENERATION_HISTORY_KEEP="${COMMENT_GENERATION_HISTORY_KEEP:-500}"
RADIO_GENERATION_HISTORY_KEEP="${RADIO_GENERATION_HISTORY_KEEP:-500}"
RADIO_CLAUDE_MODEL="${RADIO_CLAUDE_MODEL:-haiku}"
RADIO_BRIEFING_ENABLED="${RADIO_BRIEFING_ENABLED:-0}"
RADIO_BRIEFING_MAX_CHARS="${RADIO_BRIEFING_MAX_CHARS:-2000}"
RADIO_BRIEFING_MODEL="${RADIO_BRIEFING_MODEL:-claude-haiku-4-5-20251001}"
RADIO_QUALITY_CHECK_ENABLED="${RADIO_QUALITY_CHECK_ENABLED:-1}"
RADIO_MAX_RETRIES="${RADIO_MAX_RETRIES:-1}"
RADIO_QUALITY_MIN_JAPANESE_RATIO="${RADIO_QUALITY_MIN_JAPANESE_RATIO:-0.10}"
RADIO_QUALITY_MAX_REPETITIONS="${RADIO_QUALITY_MAX_REPETITIONS:-3}"
RADIO_QUALITY_SKIP_CORNERS="${RADIO_QUALITY_SKIP_CORNERS:-}"
RADIO_FACT_CHECK_ENABLED="${RADIO_FACT_CHECK_ENABLED:-1}"
RUSSIA_CELEBRATION_ENABLED="${RUSSIA_CELEBRATION_ENABLED:-0}"
ROLLBACK_POSTMORTEM_MODEL="${ROLLBACK_POSTMORTEM_MODEL:-opencode:x-preview-f-free}"
ROLLBACK_POSTMORTEM_FALLBACK="${ROLLBACK_POSTMORTEM_FALLBACK:-opencode-go:muse-spark-1.2-contributor}"
ROLLBACK_POSTMORTEM_TIMEOUT_SEC="${ROLLBACK_POSTMORTEM_TIMEOUT_SEC:-300}"
# 粛清カスケード中 (regression_streak >= 閾値) は AI postmortem をスキップし
# opencode スロット競合を減らして改善サイクル長期化=代打無限化を防ぐ
ROLLBACK_POSTMORTEM_CASCADE_SKIP_ENABLED="${ROLLBACK_POSTMORTEM_CASCADE_SKIP_ENABLED:-1}"
ROLLBACK_POSTMORTEM_CASCADE_SKIP_STREAK="${ROLLBACK_POSTMORTEM_CASCADE_SKIP_STREAK:-2}"
# 改善完了後、次の (カスケード) 改善ロックに即 PAUSE する前にメインゲームを
# 最低1ゲーム走らせる窓。soren91 代打がサイクル間で連続起動し続けるのを防ぐ
# strategy_runner が commands未消化 N連続で bridge desync を検出した時、
# eloop.sh が bridge を自動再起動して空転を自己回復する。DROP/state 更新が
# 止まった実行系は1回あたり約140秒空転するため、既定は3連続に抑える。
BRIDGE_DESYNC_AUTO_RECOVER_ENABLED="${BRIDGE_DESYNC_AUTO_RECOVER_ENABLED:-1}"
BRIDGE_DESYNC_STOP_STALE_SOREN91_ENABLED="${BRIDGE_DESYNC_STOP_STALE_SOREN91_ENABLED:-1}"
BRIDGE_DESYNC_SOREN91_STOP_TIMEOUT="${BRIDGE_DESYNC_SOREN91_STOP_TIMEOUT:-0}"
PHANTOM_GAME_AUTO_RECOVER_ENABLED="${PHANTOM_GAME_AUTO_RECOVER_ENABLED:-1}"
SOREN_BRIDGE_DESYNC_LIMIT="${SOREN_BRIDGE_DESYNC_LIMIT:-3}"
POST_IMPROVE_MAINPLAY_ENABLED="${POST_IMPROVE_MAINPLAY_ENABLED:-1}"
# TMP_STATE_DIR は後方で定義されるためリテラル指定 (= tmp/state)
POST_IMPROVE_MAINPLAY_MARKER="tmp/state/.post_improve_mainplay"
RADIO_FACT_CHECK_AGENT="${RADIO_FACT_CHECK_AGENT:-opencode:x-preview-f-free}"
# SECONDARY は旧来の FALLBACK 設定（VMでは MiniMax）より前に試す。
# これで既存 .env を変更しなくても muse → 有料DeepSeek → MiniMax の順を保証する。
RADIO_FACT_CHECK_SECONDARY="${RADIO_FACT_CHECK_SECONDARY:-opencode-go:muse-spark-1.2-contributor}"
RADIO_FACT_CHECK_FALLBACK="${RADIO_FACT_CHECK_FALLBACK:-codex:minimax-m3}"
RADIO_FACT_CHECK_TERTIARY="${RADIO_FACT_CHECK_TERTIARY:-}"
RADIO_FACT_CHECK_QUINARY="${RADIO_FACT_CHECK_QUINARY:-}"
RADIO_FACT_CHECK_CLAUDE_MODEL="${RADIO_FACT_CHECK_CLAUDE_MODEL:-$RADIO_CLAUDE_MODEL}"
RADIO_FACT_CHECK_MIN_CHARS=100
RADIO_FACT_CHECK_SKIP_CORNERS="${RADIO_FACT_CHECK_SKIP_CORNERS:-strategy,soviet}"
RADIO_FACT_CHECK_MIN_RATIO="${RADIO_FACT_CHECK_MIN_RATIO:-0.68}"
RADIO_FACT_CHECK_MAX_ABS_SHRINK="${RADIO_FACT_CHECK_MAX_ABS_SHRINK:-700}"
RADIO_FACT_CHECK_FEW_ISSUES_MAX="${RADIO_FACT_CHECK_FEW_ISSUES_MAX:-2}"
RADIO_FACT_CHECK_MIN_SIMILARITY_NOISSUES="${RADIO_FACT_CHECK_MIN_SIMILARITY_NOISSUES:-0.90}"
RADIO_FACT_CHECK_MIN_SIMILARITY_FEW_ISSUES="${RADIO_FACT_CHECK_MIN_SIMILARITY_FEW_ISSUES:-0.74}"
RADIO_FACT_CHECK_MAX_PARAGRAPH_DROP="${RADIO_FACT_CHECK_MAX_PARAGRAPH_DROP:-2}"
RADIO_WEB_GROUNDING_ENABLED="${RADIO_WEB_GROUNDING_ENABLED:-1}"
RADIO_WEB_GROUNDING_TTL_SEC="${RADIO_WEB_GROUNDING_TTL_SEC:-21600}"
RADIO_WEB_GROUNDING_MAX_SOURCES="${RADIO_WEB_GROUNDING_MAX_SOURCES:-3}"
RADIO_STATE_STALE_SEC="${RADIO_STATE_STALE_SEC:-600}"
# deferred ラジオは本文と事前生成音声の世代を照合してから再生する。
# 時報の分表示は、長時間滞留時の再レンダリングを避けるため既定では時単位。
RADIO_TIME_SYNC_ENABLED="${RADIO_TIME_SYNC_ENABLED:-1}"
RADIO_TIME_ANNOUNCE_MINUTES="${RADIO_TIME_ANNOUNCE_MINUTES:-0}"
# --- tmp/ サブディレクトリ ---
TMP_STATE_DIR="tmp/state"
TMP_MARKERS_DIR="tmp/markers"
TMP_HISTORY_DIR="tmp/history"
TMP_DEBUG_DIR="tmp/debug"
TMP_CACHE_DIR="tmp/cache"
CC_POST_LOG_FILE="$TMP_DEBUG_DIR/cc_post.log"
PHYROGENETIC_CHAT_POST_LOG_FILE="$TMP_DEBUG_DIR/phyrogenetic_chat_post.log"

RADIO_WEB_GROUNDING_CACHE_DIR="$TMP_CACHE_DIR/radio_grounding"
RADIO_STATE_FILE="$TMP_STATE_DIR/.radio_state"
RADIO_THEME_PICK_STATUS_FILE="$TMP_STATE_DIR/.radio_theme_pick_status.json"
RADIO_CORNER_STATUS_FILE="$TMP_STATE_DIR/.radio_corner_status.json"
COMMENT_GEN_STATE_FILE="$TMP_STATE_DIR/.comment_gen_state"
LAST_PHYROGENETIC_CHAT_COMMIT_FILE="$TMP_STATE_DIR/last_phyrogenetic_chat_commit.txt"
MANUAL_MERIKEN_MODE_FILE="$TMP_STATE_DIR/manual_meriken_mode.json"
RADIO_OPENCODE_PERMISSION='{"*":"deny","read":"allow","glob":"allow","grep":"allow","list":"allow","webfetch":"allow","web":"allow","web-search":"allow","external_directory":"allow"}'
COMMENT_OPENCODE_PERMISSION_DEFAULT='{"*":"deny","read":"allow","glob":"allow","grep":"allow","list":"allow","webfetch":"allow","web":"allow","web-search":"allow","external_directory":"allow"}'
COMMENT_OPENCODE_PERMISSION="${COMMENT_OPENCODE_PERMISSION:-$COMMENT_OPENCODE_PERMISSION_DEFAULT}"
COMMENT_OPENCODE_TIMEOUT="${COMMENT_OPENCODE_TIMEOUT:-45}"
COMMENT_OPENCODE_LOCK_POLL_SEC="${COMMENT_OPENCODE_LOCK_POLL_SEC:-1}"
COMMENT_OPENCODE_LOCK_MAX_WAIT_SEC="${COMMENT_OPENCODE_LOCK_MAX_WAIT_SEC:-4}"
RADIO_CLAUDE_TOOLS="${RADIO_CLAUDE_TOOLS:-default,WebSearch,WebFetch}"
COMMENT_CLAUDE_TOOLS="${COMMENT_CLAUDE_TOOLS:-default,WebSearch,WebFetch}"
COMMENT_CLAUDE_TIMEOUT="${COMMENT_CLAUDE_TIMEOUT:-60}"
COMMENT_TRY_CLAUDE_BEFORE_OPENCODE_FALLBACK="${COMMENT_TRY_CLAUDE_BEFORE_OPENCODE_FALLBACK:-0}"
COMMENT_FORCE_CLAUDE_WHEN_IMPROVING="${COMMENT_FORCE_CLAUDE_WHEN_IMPROVING:-0}"
COMMENT_RESPONSE_RETRY_MAX="${COMMENT_RESPONSE_RETRY_MAX:-1}"
IMPROVE_OPENCODE_PERMISSION='{"*":"deny","read":"allow","glob":"allow","grep":"allow","list":"allow","edit":"allow","write":"allow","external_directory":"allow"}'
RADIO_SAY_RATE=150
unset SAY_AUDIO_DEVICE
PAST_RADIO_TOPICS="$TMP_HISTORY_DIR/past_radio_topics.txt"
PAST_RADIO_THEME_KEYS="$TMP_HISTORY_DIR/.past_radio_themes.txt"
PAST_RADIO_THEME_BODIES="$TMP_HISTORY_DIR/past_radio_theme_bodies.txt"
PAST_RADIO_THEME_HISTORY_KEEP="${PAST_RADIO_THEME_HISTORY_KEEP:-400}"
PAST_NEWS_READ="$TMP_HISTORY_DIR/past_news_read.txt"
PAST_NEWS_READ_KEYS="$TMP_HISTORY_DIR/past_news_read_keys.txt"
PAST_NEWS_URL_HASHES="$TMP_HISTORY_DIR/past_news_url_hashes.txt"
PAST_NEWS_TOPIC_KEYS="$TMP_HISTORY_DIR/past_news_topic_keys.txt"
PAST_JIJI_URL_HASHES="$TMP_HISTORY_DIR/past_jiji_url_hashes.txt"
PAST_NEWS_READ_SOURCES="$TMP_HISTORY_DIR/past_news_read_sources.txt"
RUSSIA_CREATION_HISTORY_FILE="$TMP_HISTORY_DIR/russia_creation_history.tsv"
SOVIET_CREATION_HISTORY_FILE="$TMP_HISTORY_DIR/soviet_creation_history.tsv"
# カードガチャで全種コンプリート(N種中N種所持)を達成済みのユーザー一覧。
# 一度祝福したユーザーは記録し、以後はコンプリートに毎回触れないようにする。
GACHA_COMPLETED_USERS_FILE="$TMP_HISTORY_DIR/gacha_completed_users.txt"
CELEBRATION_HISTORY_KEEP_LINES="${CELEBRATION_HISTORY_KEEP_LINES:-200}"
COMMENT_CELEBRATION_HISTORY_ITEMS="${COMMENT_CELEBRATION_HISTORY_ITEMS:-12}"
MAIN_STRATEGY_ADVICE_FILE="advice.md"
SOREN91_STRATEGY_ADVICE_FILE="advice91.md"
COMMENT_ADVICE_FILE="advice_comment.md"
CODEX_ADVICE_FILE="data/codex_advice.md"
STRATEGY_ADVICE_FILE="$MAIN_STRATEGY_ADVICE_FILE"
CODEX_BUG_QUEUE_DIR="${CODEX_BUG_QUEUE_DIR:-tmp/codex_bug_queue}"
CODEX_BUG_DISPATCH_LOCK_DIR="$TMP_STATE_DIR/.codex_bug_dispatch.lock"
CODEX_BUG_DISPATCH_DEDUP_FILE="$TMP_STATE_DIR/codex_bug_dispatch_hashes.log"
CODEX_BUG_DISPATCH_LAST_FILE="$TMP_STATE_DIR/codex_bug_dispatch_last.ts"
CODEX_BUG_DISPATCH_LOG_DIR="$TMP_DEBUG_DIR/codex_bug_dispatch"

IMPROVE_STATE_FILE="$ELOOP_LIB_DIR/$TMP_STATE_DIR/improve_state.json"
IMPROVE_LOCK_FILE="$ELOOP_LIB_DIR/tmp/improve.lock"
# 改善ジョブ開始時の入力バッチを別ファイルへ原子的に退避する。
# failed_no_apply の harvest 時に improve.lock が失われていても、同一
# strategy hash の有効なバッチだけを復元してバックオフ再試行できる。
IMPROVE_RETRY_BATCH_FILE="$ELOOP_LIB_DIR/$TMP_STATE_DIR/improve_retry_batch.json"
# spawn 排他 mutex: dual-spawner (soren_loop 本流 + improve_daemon watchdog) の
# 二重起動レースを mkdir atomic で防ぐ。owner ファイルで所有者検証付き。
IMPROVE_SPAWN_LOCK_DIR="$ELOOP_LIB_DIR/$TMP_STATE_DIR/.improve_spawn.lock"
IMPROVE_SPAWN_LOCK_TTL="${IMPROVE_SPAWN_LOCK_TTL:-90}"
# Fix0: 復旧アクター調停 (guardian / _ensure_bridge_alive / soviet_watchdog 共通)
RUNTIME_RECOVERY_LOCK_DIR="$ELOOP_LIB_DIR/$TMP_STATE_DIR/.runtime_recovery.lock"
RUNTIME_RECOVERY_LOCK_TTL="${RUNTIME_RECOVERY_LOCK_TTL:-120}"
RUNTIME_RECOVERY_TAINT_FILE="$ELOOP_LIB_DIR/$TMP_STATE_DIR/runtime_recovery.taint"
RUNTIME_RECOVERY_TAINT_WINDOW="${RUNTIME_RECOVERY_TAINT_WINDOW:-180}"
IMPROVE_DAEMON_PID_FILE="$TMP_STATE_DIR/improve_daemon.pid"
IMPROVE_AI_LOG_FILE="$ELOOP_LIB_DIR/$TMP_DEBUG_DIR/improve_ai.log"
IMPROVE_OVERLAY_HTML_FILE="${IMPROVE_OVERLAY_HTML_FILE:-$ELOOP_LIB_DIR/$TMP_STATE_DIR/improve_overlay.html}"
IMPROVE_OVERLAY_LOG_FILE="$ELOOP_LIB_DIR/$TMP_DEBUG_DIR/improve_overlay.log"
IMPROVE_OVERLAY_SOURCE="${OBS_IMPROVE_OVERLAY_SOURCE:-improveOverlay}"
IMPROVE_OVERLAY_REFRESH_SEC="${IMPROVE_OVERLAY_REFRESH_SEC:-2}"
IMPROVE_FAST_ESCAPE_OVERLAY_HOLD_SEC="${IMPROVE_FAST_ESCAPE_OVERLAY_HOLD_SEC:-45}"
EVENT_OVERLAY_EVENTS_FILE="${EVENT_OVERLAY_EVENTS_FILE:-$ELOOP_LIB_DIR/$TMP_STATE_DIR/overlay_events.jsonl}"
EVENT_OVERLAY_HTML_FILE="${EVENT_OVERLAY_HTML_FILE:-$ELOOP_LIB_DIR/$TMP_STATE_DIR/event_overlay.html}"
EVENT_OVERLAY_KEEP_EVENTS="${EVENT_OVERLAY_KEEP_EVENTS:-180}"
EVENT_OVERLAY_VISIBLE_SEC="${EVENT_OVERLAY_VISIBLE_SEC:-18}"
EVENT_OVERLAY_SOURCE="${OBS_EVENT_OVERLAY_SOURCE:-eventOverlay}"
CODEX_WORK_OVERLAY_STATE_FILE="$ELOOP_LIB_DIR/$TMP_STATE_DIR/codex_work_indicator.json"
STATUS_OVERLAY_HTML_FILE="${STATUS_OVERLAY_HTML_FILE:-$ELOOP_LIB_DIR/$TMP_STATE_DIR/status_overlay.html}"
STATUS_OVERLAY_SOURCE="${STATUS_OVERLAY_SOURCE:-${OBS_STATS_OVERLAY_SOURCE:-${OBS_STATUS_OVERLAY_SOURCE:-statsOverlay}}}"
STATS_OVERLAY_SOURCE="$STATUS_OVERLAY_SOURCE"
STATUS_OVERLAY_WIDTH="${STATUS_OVERLAY_WIDTH:-560}"
STATUS_OVERLAY_HEIGHT="${STATUS_OVERLAY_HEIGHT:-820}"
STATUS_OVERLAY_OBS_X="${STATUS_OVERLAY_OBS_X:-24}"
STATUS_OVERLAY_OBS_Y="${STATUS_OVERLAY_OBS_Y:-300}"
STATUS_OVERLAY_OBS_SCALE_X="${STATUS_OVERLAY_OBS_SCALE_X:-0.86}"
STATUS_OVERLAY_OBS_SCALE_Y="${STATUS_OVERLAY_OBS_SCALE_Y:-0.78}"
STATUS_OVERLAY_OBS_TRANSFORM_ENABLED="${STATUS_OVERLAY_OBS_TRANSFORM_ENABLED:-1}"
SHOW_STATUS_OVERLAY_HTML_FILE="${SHOW_STATUS_OVERLAY_HTML_FILE:-$ELOOP_LIB_DIR/$TMP_STATE_DIR/show_status_overlay.html}"
SHOW_STATUS_OVERLAY_SOURCE="${SHOW_STATUS_OVERLAY_SOURCE:-${OBS_OPS_OVERLAY_SOURCE:-${OBS_SHOW_STATUS_OVERLAY_SOURCE:-opsOverlay}}}"
BROADCAST_TOP_OVERRIDE_FILE="${BROADCAST_TOP_OVERRIDE_FILE:-$ELOOP_LIB_DIR/$TMP_STATE_DIR/broadcast_top_override.json}"
export BROADCAST_TOP_OVERRIDE_FILE
OPS_OVERLAY_SOURCE="$SHOW_STATUS_OVERLAY_SOURCE"
SHOW_STATUS_OVERLAY_WIDTH="${SHOW_STATUS_OVERLAY_WIDTH:-520}"
SHOW_STATUS_OVERLAY_HEIGHT="${SHOW_STATUS_OVERLAY_HEIGHT:-680}"
SHOW_STATUS_OVERLAY_OBS_X="${SHOW_STATUS_OVERLAY_OBS_X:-1448}"
SHOW_STATUS_OVERLAY_OBS_Y="${SHOW_STATUS_OVERLAY_OBS_Y:-300}"
SHOW_STATUS_OVERLAY_OBS_SCALE_X="${SHOW_STATUS_OVERLAY_OBS_SCALE_X:-0.86}"
SHOW_STATUS_OVERLAY_OBS_SCALE_Y="${SHOW_STATUS_OVERLAY_OBS_SCALE_Y:-0.78}"
IMPROVE_AI_LOG_KEEP_LINES=4000
IMPROVE_AI_LOG_TRIM_LINES=8000
IMPROVE_AUDIO_SUMMARY_ENABLED="${IMPROVE_AUDIO_SUMMARY_ENABLED:-1}"
IMPROVE_AUDIO_SUMMARY_INTERVAL_SEC="${IMPROVE_AUDIO_SUMMARY_INTERVAL_SEC:-900}"
IMPROVE_AUDIO_SUMMARY_STATE_FILE="$TMP_STATE_DIR/improve_audio_summary_last.json"
IMPROVE_AUDIO_SUMMARY_SPEAKER="${IMPROVE_AUDIO_SUMMARY_SPEAKER:-${SOREN91_VOICEVOX_SPEAKER:-46}}"
AUDIO_WORKER_WARNING_INTERVAL_SEC="${AUDIO_WORKER_WARNING_INTERVAL_SEC:-900}"
SOREN_PAUSE_LOG_INTERVAL_SEC="${SOREN_PAUSE_LOG_INTERVAL_SEC:-900}"
COMMENT_CLAUDE_LOG_FILE="$ELOOP_LIB_DIR/$TMP_DEBUG_DIR/comment_claude.log"
IMPROVE_BACKOFF_LOG_INTERVAL_SEC="${IMPROVE_BACKOFF_LOG_INTERVAL_SEC:-900}"
# ピーク時間帯回避: deepseek-v4-flash はピーク帯 (UTC 01:00-04:00, 06:00-10:00 =
# JST 10:00-13:00, 15:00-19:00) で入出力とも2倍課金のため、通常改善ロックの消費を
# オフピークまで遅延する。.env で IMPROVE_PEAK_HOUR_DEFER_ENABLED=0 とすれば即無効化。
# 現在は既定で無効化し、代わりに IMPROVE_PEAK_CHAIN (ピーク専用チェーン) を使用する。
IMPROVE_PEAK_HOUR_DEFER_ENABLED="${IMPROVE_PEAK_HOUR_DEFER_ENABLED:-0}"
IMPROVE_PEAK_HOUR_UTC_RANGES="${IMPROVE_PEAK_HOUR_UTC_RANGES:-01:00-04:00,06:00-10:00}"
IMPROVE_PEAK_DEFER_MAX_WAIT_SEC="${IMPROVE_PEAK_DEFER_MAX_WAIT_SEC:-16200}"     # 4.5h バックストップ
IMPROVE_PEAK_DEFER_FORCE_ACC_PCT="${IMPROVE_PEAK_DEFER_FORCE_ACC_PCT:-200}"     # 合算蓄積が閾値の200%で強制実行
IMPROVE_PEAK_DEFER_LOG_INTERVAL_SEC="${IMPROVE_PEAK_DEFER_LOG_INTERVAL_SEC:-${IMPROVE_BACKOFF_LOG_INTERVAL_SEC:-900}}"
# ラジオ生成のピーク時間帯回避 (旧 issue #14: RADIO_PEAK_HOUR_DEFER_ENABLED で新規生成を
# 丸ごと止める方式) は撤去済み。代わりに上記 PEAK_HOURS_* (RADIO_AGENTS/COMMENT_AGENTS の
# 候補順序入替え、および下記 PEAK_HOURS_QUEUE_GATE_ENABLED によるキュー0件までの抑止) を使う。
IMPROVE_RUN_CMD_TIMEOUT_SEC="${IMPROVE_RUN_CMD_TIMEOUT_SEC:-1800}"
# Stage1 分析フェーズのモデルあたりタイムアウト。実測 (2026-08-22 ai_stats n=10) では
# 成功が 48-1298s・900s 超えが 30% だったため 1100 (成功の90%をカバー)。
# wall timeout 圧迫を避けるため RUN より短く、リトライ数は下記で2に限定する。
IMPROVE_ANALYZE_CMD_TIMEOUT_SEC="${IMPROVE_ANALYZE_CMD_TIMEOUT_SEC:-1100}"
IMPROVE_ANALYZE_PRIMARY_RETRIES="${IMPROVE_ANALYZE_PRIMARY_RETRIES:-2}"
IMPROVE_REVIEW_CMD_TIMEOUT_SEC="${IMPROVE_REVIEW_CMD_TIMEOUT_SEC:-600}"
IMPROVE_REVIEW_PRIMARY_RETRIES="${IMPROVE_REVIEW_PRIMARY_RETRIES:-1}"
IMPROVE_FIX_CMD_TIMEOUT_SEC="${IMPROVE_FIX_CMD_TIMEOUT_SEC:-600}"
IMPROVE_OPENCODE_LOCK_MAX_WAIT_SEC="${IMPROVE_OPENCODE_LOCK_MAX_WAIT_SEC:-180}"
IMPROVE_WALL_TIMEOUT="${IMPROVE_WALL_TIMEOUT:-3600}"
IMPROVE_STALE_WATCHDOG_SEC="${IMPROVE_STALE_WATCHDOG_SEC:-600}"
IMPROVE_HUNG_HARVEST_ENABLED="${IMPROVE_HUNG_HARVEST_ENABLED:-1}"
IMPROVE_HUNG_QUARANTINE_FILE="$TMP_STATE_DIR/improve_hung_quarantine.jsonl"
IMPROVE_HUNG_REQUIRE_EVAL_STALE="${IMPROVE_HUNG_REQUIRE_EVAL_STALE:-1}"
EVAL_SCORE_HISTORY_FILE="${EVAL_SCORE_HISTORY_FILE:-eval_score_history.txt}"
SOREN91_IMPROVE_HUNG_HARVEST_ENABLED="${SOREN91_IMPROVE_HUNG_HARVEST_ENABLED:-1}"
SOREN91_IMPROVE_HUNG_SEC="${SOREN91_IMPROVE_HUNG_SEC:-900}"
SOREN91_IMPROVE_HUNG_QUARANTINE_FILE="$TMP_STATE_DIR/soren91_improve_hung_quarantine.jsonl"
POST_IMPROVE_SOREN91_SESSION_IMPROVE_ENABLED="${POST_IMPROVE_SOREN91_SESSION_IMPROVE_ENABLED:-0}"
ACCUMULATED_GAMES_FILE="$TMP_STATE_DIR/accumulated_games.json"
ROLLING_SCORES_FILE="$TMP_STATE_DIR/rolling_scores.json"
CURRENT_STRATEGY_RUN_FILE="$TMP_STATE_DIR/current_strategy_run.json"
REJECTED_HASHES_FILE="$TMP_HISTORY_DIR/rejected_hashes.txt"
REJECTED_HASH_META_FILE="$TMP_STATE_DIR/rejected_hash_metrics.json"
REJECTED_REEVALUATE_TTL_SEC="${REJECTED_REEVALUATE_TTL_SEC:-21600}"
ROLLBACK_TARGET_COOLDOWN_FILE="$TMP_STATE_DIR/rollback_target_cooldown.json"
ROLLBACK_TARGET_COOLDOWN_SEC="${ROLLBACK_TARGET_COOLDOWN_SEC:-3600}"
ROLLBACK_REVALIDATE_TARGET_ENABLED="${ROLLBACK_REVALIDATE_TARGET_ENABLED:-1}"
LAST_ROLLBACK_PAIR_FILE="$TMP_STATE_DIR/last_rollback_pair.json"
ROLLBACK_ANALYSIS_FILE="$TMP_STATE_DIR/last_rollback_analysis.md"
ROLLBACK_POSTMORTEM_FILE="$TMP_STATE_DIR/last_rollback_postmortem.md"
ROLLBACK_POSTMORTEM_CONTEXT_FILE="$TMP_STATE_DIR/last_rollback_postmortem_context.md"
ROLLBACK_POSTMORTEM_PID_FILE="$TMP_STATE_DIR/rollback_postmortem.pid"
ROLLBACK_POSTMORTEM_AI_LOG_FILE="$ELOOP_LIB_DIR/$TMP_DEBUG_DIR/rollback_postmortem_ai.log"
BEST_STRATEGY_ANCHOR_FILE="$TMP_STATE_DIR/best_strategy_anchor.json"
ACTIVE_BRANCH_FILE="$TMP_STATE_DIR/active_branch.json"
RUNTIME_RECOVERY_GATE_FILE="$TMP_STATE_DIR/recovery_gate"
REGRESSION_ROLLBACK_DONE=0
REGRESSION_ROLLBACK_HASH=""
MIN_GAMES_BEFORE_IMPROVE="${MIN_GAMES_BEFORE_IMPROVE:-12}"
# 試合単位の自動成績チャットは停止し、改善サイクル単位の解説だけを
# AI生成して audio_worker へ渡す。必要な場合だけ環境変数で旧投稿を戻せる。
BATCH_COMMENTARY_ENABLED="${BATCH_COMMENTARY_ENABLED:-1}"
BATCH_COMMENTARY_AGENTS="${BATCH_COMMENTARY_AGENTS:-${RADIO_AGENTS:-}}"
BATCH_COMMENTARY_TIMEOUT_SEC="${BATCH_COMMENTARY_TIMEOUT_SEC:-120}"
BATCH_COMMENTARY_MAX_CHARS="${BATCH_COMMENTARY_MAX_CHARS:-420}"
BATCH_COMMENTARY_CONTEXT_MAX_CHARS="${BATCH_COMMENTARY_CONTEXT_MAX_CHARS:-2400}"
GAME_RESULT_CHAT_ENABLED="${GAME_RESULT_CHAT_ENABLED:-0}"
# 探索モード (EXPLORE_MODE=1) では探索専用の改善サイクルに上書きする。
# 環境変数 EXPLORE_MODE は .env 再読込やホットリロードで失われる可能性があるため、
# explore.sh が作成する tmp/state/explore_mode マーカの存在を基準にする。
# これにより soren_loop.sh が毎周回 .env を再読込しても MIN_GAMES_BEFORE_IMPROVE=100 に
# 戻らない。EXPLORE_MIN_GAMES_BEFORE_IMPROVE 未指定時は 12。配信モードには影響しない。
if [ -f "$ELOOP_LIB_DIR/tmp/state/explore_mode" ]; then
	MIN_GAMES_BEFORE_IMPROVE="${EXPLORE_MIN_GAMES_BEFORE_IMPROVE:-12}"
fi
MIN_GAMES_BEFORE_REGRESSION="${MIN_GAMES_BEFORE_REGRESSION:-12}"
EARLY_OBJECTIVE_REGRESSION_ENABLED="${EARLY_OBJECTIVE_REGRESSION_ENABLED:-1}"
EARLY_OBJECTIVE_REGRESSION_MIN_GAMES="${EARLY_OBJECTIVE_REGRESSION_MIN_GAMES:-4}"
EARLY_OBJECTIVE_REGRESSION_MIN_BEST_TYPE="${EARLY_OBJECTIVE_REGRESSION_MIN_BEST_TYPE:-15}"
export DIRECT_ANCHOR_PROMOTION_OBJECTIVE_GUARD_ENABLED="${DIRECT_ANCHOR_PROMOTION_OBJECTIVE_GUARD_ENABLED:-1}"
CURRENT_RUN_FRESH_OBJECTIVE_REGRESSION_ENABLED="${CURRENT_RUN_FRESH_OBJECTIVE_REGRESSION_ENABLED:-1}"
CURRENT_RUN_FRESH_OBJECTIVE_REGRESSION_MIN_GAMES="${CURRENT_RUN_FRESH_OBJECTIVE_REGRESSION_MIN_GAMES:-2}"
CURRENT_RUN_FRESH_OBJECTIVE_SAME_HASH_EARLY_LOCK_ENABLED="${CURRENT_RUN_FRESH_OBJECTIVE_SAME_HASH_EARLY_LOCK_ENABLED:-1}"
CURRENT_RUN_FRESH_OBJECTIVE_SAME_HASH_MIN_BEST_TYPE="${CURRENT_RUN_FRESH_OBJECTIVE_SAME_HASH_MIN_BEST_TYPE:-14}"
CURRENT_RUN_FRESH_OBJECTIVE_SAME_HASH_LOW_STAGE_MIN_GAMES="${CURRENT_RUN_FRESH_OBJECTIVE_SAME_HASH_LOW_STAGE_MIN_GAMES:-${CURRENT_RUN_FRESH_OBJECTIVE_LOW_STAGE_MIN_GAMES:-2}}"
CURRENT_RUN_FRESH_OBJECTIVE_SAME_HASH_LOW_STAGE_MAX_BEST_TYPE="${CURRENT_RUN_FRESH_OBJECTIVE_SAME_HASH_LOW_STAGE_MAX_BEST_TYPE:-${CURRENT_RUN_FRESH_OBJECTIVE_LOW_STAGE_MAX_BEST_TYPE:-13}}"
SAME_HASH_BACKSLIDE_RESET_ENABLED="${SAME_HASH_BACKSLIDE_RESET_ENABLED:-1}"
SAME_HASH_BACKSLIDE_MIN_EXTRA_GAMES="${SAME_HASH_BACKSLIDE_MIN_EXTRA_GAMES:-4}"
MIN_GAMES_FOR_BEST_ROLLBACK="${MIN_GAMES_FOR_BEST_ROLLBACK:-12}"
OBJECTIVE_ANCHOR_PRIORITY_ENABLED="${OBJECTIVE_ANCHOR_PRIORITY_ENABLED:-0}"
OBJECTIVE_ANCHOR_MIN_COMP_RATIO="${OBJECTIVE_ANCHOR_MIN_COMP_RATIO:-0.90}"
OBJECTIVE_ANCHOR_MAX_COMP_GAP="${OBJECTIVE_ANCHOR_MAX_COMP_GAP:-1500}"
# 2nd-Russia/ソ連フロンティア保護: 1試合だけのフロック(現状の全frontier株が該当)では
# anchor/rollbackで優先せず、frontier(T15x2 もしくは T15x1+T14x2)を N 試合以上で再現した
# 戦略のみ目的進捗として扱う。単発ロシア(T15x1単独)は対象外 = 2026-05-25のスコア崩壊を再現しない。
OBJECTIVE_FRONTIER_MIN_GAMES="${OBJECTIVE_FRONTIER_MIN_GAMES:-2}"
REGRESSION_MAX_RANK="${REGRESSION_MAX_RANK:-20}"
RANK_LCB_Z="${RANK_LCB_Z:-1.28}"
RANK_WEIGHT_P50="${RANK_WEIGHT_P50:-0.55}"
RANK_WEIGHT_P25="${RANK_WEIGHT_P25:-0.30}"
RANK_WEIGHT_LCB="${RANK_WEIGHT_LCB:-0.15}"
REGRESSION_COMPOSITE_RATIO="${REGRESSION_COMPOSITE_RATIO:-0.88}"
REGRESSION_P50_RATIO="${REGRESSION_P50_RATIO:-0.85}"
REGRESSION_P25_RATIO="${REGRESSION_P25_RATIO:-0.80}"
REGRESSION_MIN_COMP_GAP="${REGRESSION_MIN_COMP_GAP:-1000}"
REGRESSION_MIN_P50_GAP="${REGRESSION_MIN_P50_GAP:-800}"
REGRESSION_MIN_P25_GAP="${REGRESSION_MIN_P25_GAP:-1600}"
REGRESSION_MIN_BREACH_COUNT="${REGRESSION_MIN_BREACH_COUNT:-2}"
BRANCH_MAX_DEPTH="${BRANCH_MAX_DEPTH:-4}"
BRANCH_MAX_GAMES=$((MIN_GAMES_BEFORE_IMPROVE * 4)) # 4サイクル分 (base: 24*4=96)
BRANCH_PATIENCE="${BRANCH_PATIENCE:-3}"
BRANCH_HARD_COMP_GAP="${BRANCH_HARD_COMP_GAP:-2800}"
BRANCH_HARD_P50_GAP="${BRANCH_HARD_P50_GAP:-2200}"
BRANCH_HARD_P25_GAP="${BRANCH_HARD_P25_GAP:-3300}"
BRANCH_HARD_MIN_BREACH_COUNT="${BRANCH_HARD_MIN_BREACH_COUNT:-2}"
REGRESSION_TREND_SHORT_WINDOW="${REGRESSION_TREND_SHORT_WINDOW:-50}"
REGRESSION_TREND_LONG_WINDOW="${REGRESSION_TREND_LONG_WINDOW:-100}"
REGRESSION_TREND_SHORT_RATIO="${REGRESSION_TREND_SHORT_RATIO:-0.94}"
REGRESSION_TREND_LONG_RATIO="${REGRESSION_TREND_LONG_RATIO:-0.95}"
ROLLBACK_TREND_GRACE_ENABLED="${ROLLBACK_TREND_GRACE_ENABLED:-1}"
ROLLBACK_TREND_GRACE_WINDOW="${ROLLBACK_TREND_GRACE_WINDOW:-50}"
ROLLBACK_TREND_GRACE_MIN_PRIOR="${ROLLBACK_TREND_GRACE_MIN_PRIOR:-50}"
ROLLBACK_TREND_GRACE_MIN_DELTA="${ROLLBACK_TREND_GRACE_MIN_DELTA:-0}"
EARLY_COMP_TOP_GAP_ENABLED="${EARLY_COMP_TOP_GAP_ENABLED:-1}"
EARLY_COMP_TOP_GAP_MIN_GAMES="${EARLY_COMP_TOP_GAP_MIN_GAMES:-4}"
EARLY_COMP_TOP_GAP_MIN_RATIO="${EARLY_COMP_TOP_GAP_MIN_RATIO:-0.85}"
# Russia advantage grace: suppress early_comp_top_gap rollback for strategies with
# MORE russia than the anchor, for up to N games. 0 = disabled (old behavior).
EARLY_COMP_TOP_GAP_RUSSIA_ADVANTAGE_GRACE_GAMES="${EARLY_COMP_TOP_GAP_RUSSIA_ADVANTAGE_GRACE_GAMES:-16}"
export EARLY_COMP_TOP_GAP_RUSSIA_ADVANTAGE_GRACE_GAMES
# 2026-08-25: 段階到達率ゲート (lost_turkmenistan/ukraine/kazakhstan_gate) の統計化。
# 02:26 v727 (n=13, breach 0, comp 優位) が T14 1/13 vs 6/25 で、05:06 rollback 先 (russia 2 vs 1,
# comp -57) が T11 41/43 vs 25/25 で粛清された再発防止。率差 >= MIN_RATE_GAP かつ片側 Fisher
# p <= ALPHA のときだけ発火。STAT_ENABLED=0 で旧挙動。NONINFERIOR_GRACE は breach 0 かつ
# ロシア数非劣後 (RUSSIA_MIN_EXPECTED: anchor 率 x 現 n がこれ未満なら差は観測不能とみなす)。
# check_regression の heredoc は os.environ 経由で同じ既定値を持つ (export 必須)。
STAGE_GATE_STAT_ENABLED="${STAGE_GATE_STAT_ENABLED:-1}"
export STAGE_GATE_STAT_ENABLED
STAGE_GATE_STAT_ALPHA="${STAGE_GATE_STAT_ALPHA:-0.05}"
export STAGE_GATE_STAT_ALPHA
STAGE_GATE_MIN_RATE_GAP="${STAGE_GATE_MIN_RATE_GAP:-0.10}"
export STAGE_GATE_MIN_RATE_GAP
STAGE_GATE_RUSSIA_MIN_EXPECTED="${STAGE_GATE_RUSSIA_MIN_EXPECTED:-1.0}"
export STAGE_GATE_RUSSIA_MIN_EXPECTED
STAGE_GATE_GRACE_COMP_GAP_RATIO="${STAGE_GATE_GRACE_COMP_GAP_RATIO:-0.25}"
export STAGE_GATE_GRACE_COMP_GAP_RATIO
# 2026-08-25 v728: analyze_board で「着地モデル上ターゲットに直乗りし横重なり>=50%・柱内の他駒上端が0.05以上低い」
# 直撃を has_obstruction の誤降格から守る (1=DIRECT, 2=NEAR 昇格のみ・降格なし, 0=旧挙動)。切替は
# ./set_toggle.sh ANALYZE_BOARD_VERTICAL_LANE_DIRECT=0 (KEY=VALUE 形式)。
# analyze_board.py が毎回 os.environ を読む (runner はゲーム毎プロセス → 次ゲームから有効)。
ANALYZE_BOARD_VERTICAL_LANE_DIRECT="${ANALYZE_BOARD_VERTICAL_LANE_DIRECT:-1}"
export ANALYZE_BOARD_VERTICAL_LANE_DIRECT
# 2026-08-25 v729: 併合後ピース上端の較正 (2=併合拒否判定のみ較正[既定], 1=候補自身の crosses_deadline にも適用,
# 0=旧式)。mode 2 は「merge_result_crosses ⇒ crosses_deadline」の不変条件により締切安全プールが縮まないことが
# 構造的に保証される (311,232 候補で違反 0)。mode 1 はその保証が無い (800 盤面で実害 0 だが未保証) ので既定にしない。
# 実効果: 「交差しない非併合配置」→「自身は交差するが併合結果は線下の DIRECT」への置換が約 0.6% のターンで起きる。旧式は実測より平均 +1.05 過大で、直撃併合を締切理由で誤拒否していた。切替は
# ./set_toggle.sh ANALYZE_BOARD_MERGE_TOP_MODEL=0 (次ゲームから)。
ANALYZE_BOARD_MERGE_TOP_MODEL="${ANALYZE_BOARD_MERGE_TOP_MODEL:-2}"
export ANALYZE_BOARD_MERGE_TOP_MODEL
# 解析器の壁反射半幅: 1=当たり判定半幅+0.30 (実測較正), 0=旧式スプライト半径 (既定)。
# ./set_toggle.sh ANALYZE_BOARD_WALL_CLAMP=1 (次ゲームから)。decide hash には映らない (analyzer_modes に記録)。
ANALYZE_BOARD_WALL_CLAMP="${ANALYZE_BOARD_WALL_CLAMP:-0}"
export ANALYZE_BOARD_WALL_CLAMP
# インターリーブ A/B (strategy/ab_interleave.sh): 代替戦略ファイルを指定すると試合ごとに root(A)/代替(B) を
# SOREN_AB_PATTERN (既定 ABBA) で交互実行する。開始/終了は tools/ab_ctl.sh。空 = 無効 (既定)。
SOREN_AB_ALT_STRATEGY="${SOREN_AB_ALT_STRATEGY:-}"
SOREN_AB_PATTERN="${SOREN_AB_PATTERN:-ABBA}"
export SOREN_AB_ALT_STRATEGY SOREN_AB_PATTERN
# A/B ゲート (strategy/ab_gate.sh): 改善候補を root に適用せず A/B で採否判定。1=有効 (既定 0)。
# AB_GATE_DRY_RUN=1 (既定) は判定をログするだけ。看板は .env を直接読む (_ab_env_value) ので set_toggle で即時。
AB_GATE_ENABLED="${AB_GATE_ENABLED:-0}"
AB_GATE_DRY_RUN="${AB_GATE_DRY_RUN:-1}"
AB_GATE_LOOKS="${AB_GATE_LOOKS:-19,37}"
AB_GATE_MAX_BLOCKS="${AB_GATE_MAX_BLOCKS:-37}"
AB_GATE_FUTILITY_UCB_DELTA="${AB_GATE_FUTILITY_UCB_DELTA:-150}"
export AB_GATE_ENABLED AB_GATE_DRY_RUN AB_GATE_LOOKS AB_GATE_MAX_BLOCKS AB_GATE_FUTILITY_UCB_DELTA
# 2026-08-25: strategy_runner の静止判定 (実測: 従来は振動の一瞬の凪を静止と誤認し、新駒出現時に中央値 27 駒が
# awake)。SOREN_SETTLE_REQUIRED=連続静止観測回数 (POLL_INTERVAL 0.15s 間隔、既定 1=従来)、
# SOREN_SETTLE_MAX_SPEED2=静止とみなす速度^2 上限 (既定 0.1)、SOREN_SETTLE_MAX_AWAKE=awake 駒数上限 (-1=無視)。
# runner はゲーム毎の新プロセスなので .env 変更は次ゲームから有効。記録は game_history の "settle" フィールド。
SOREN_SETTLE_REQUIRED="${SOREN_SETTLE_REQUIRED:-1}"
export SOREN_SETTLE_REQUIRED
SOREN_SETTLE_MAX_SPEED2="${SOREN_SETTLE_MAX_SPEED2:-0.1}"
export SOREN_SETTLE_MAX_SPEED2
SOREN_SETTLE_MAX_AWAKE="${SOREN_SETTLE_MAX_AWAKE:--1}"
export SOREN_SETTLE_MAX_AWAKE
STAGE_GATE_NONINFERIOR_GRACE="${STAGE_GATE_NONINFERIOR_GRACE:-1}"
export STAGE_GATE_NONINFERIOR_GRACE
STAGE_ACHIEVEMENT_REGRESSION_ENABLED="${STAGE_ACHIEVEMENT_REGRESSION_ENABLED:-1}"
STAGE_ACHIEVEMENT_REGRESSION_MIN_GAMES="${STAGE_ACHIEVEMENT_REGRESSION_MIN_GAMES:-4}"
STAGE_ACHIEVEMENT_GATE_MIN_RATE="${STAGE_ACHIEVEMENT_GATE_MIN_RATE:-0.80}"
STAGE_ACHIEVEMENT_GATE_TYPES="${STAGE_ACHIEVEMENT_GATE_TYPES:-12,13,14,15}"

# --- 統計的判定ゲート (2026-08-20 新設, soren-stat-gate-design.md 参照) ---
#   実測根拠: 同一戦略同士でも現行ルールは 17.8-23.6% の頻度でロールバックする
#             (直近クリーン期間 n=3698 の実分布でブートストラップ, 3000試行)。
#             anchor の winner's curse は n=12/K=20 で comp +1585 / p50 +2004 と
#             REGRESSION_MIN_COMP_GAP/MIN_P50_GAP を単独で超過する。
#   Phase 0 時点では STAT_GATE_MODE=off で lib/eval_stats.py のどの関数からも
#   呼ばれていない(挙動変更ゼロ)。Phase 2 以降で strategy/regression.sh に
#   shadow→enforce の順で配線する。
STAT_GATE_MODE="${STAT_GATE_MODE:-off}"          # off | shadow | enforce
STAT_STATISTIC="${STAT_STATISTIC:-wmean}"
STAT_WINSOR_LO_Q="${STAT_WINSOR_LO_Q:-0.05}"
STAT_WINSOR_HI_Q="${STAT_WINSOR_HI_Q:-0.95}"
STAT_LOOKS="${STAT_LOOKS:-24,48,72,100}"
STAT_HARD_MIN_N="${STAT_HARD_MIN_N:-16}"
STAT_HARD_LOOK_STRIDE="${STAT_HARD_LOOK_STRIDE:-8}"
STAT_HARD_LOOK_K="${STAT_HARD_LOOK_K:-11}"
STAT_ALPHA_SOFT="${STAT_ALPHA_SOFT:-0.05}"
STAT_ALPHA_HARD="${STAT_ALPHA_HARD:-0.01}"
STAT_ALPHA_PROMOTE="${STAT_ALPHA_PROMOTE:-0.01}"
STAT_ALPHA_NONINF="${STAT_ALPHA_NONINF:-0.05}"
STAT_DELTA_SOFT="${STAT_DELTA_SOFT:-500}"
STAT_DELTA_HARD="${STAT_DELTA_HARD:-2000}"
STAT_DELTA_PROMOTE="${STAT_DELTA_PROMOTE:-500}"
STAT_DELTA_HARMLESS="${STAT_DELTA_HARMLESS:-1500}"
STAT_ANCHOR_MIN_N="${STAT_ANCHOR_MIN_N:-100}"
STAT_ANCHOR_SCORE_KEEP="${STAT_ANCHOR_SCORE_KEEP:-200}"
STAT_ANCHOR_MIN_N_FALLBACK="${STAT_ANCHOR_MIN_N_FALLBACK:-1}"
STAT_ANCHOR_MAX_AGE_GAMES="${STAT_ANCHOR_MAX_AGE_GAMES:-2000}"
STAT_PROMOTE_HOLDOUT_N="${STAT_PROMOTE_HOLDOUT_N:-48}"
STAT_TIEBREAK_ORDER="${STAT_TIEBREAK_ORDER:-soviet,frontier,best_max_type,keep_current}"
# python3 heredoc から os.environ.get() で読むには export が必須。無いと
# Phase 2 で STAT_GATE_MODE を config.sh の既定値変更で 1 にしても heredoc
# 側からは見えずサイレントに no-op になる(Phase 1 実装レビューで発見した
# INSTADEATH_SPLIT_ENABLED の同型バグ, R3, を STAT_* にも先回りで適用)。
export STAT_GATE_MODE STAT_STATISTIC STAT_WINSOR_LO_Q STAT_WINSOR_HI_Q STAT_LOOKS
export STAT_HARD_MIN_N STAT_HARD_LOOK_STRIDE STAT_HARD_LOOK_K
export STAT_ALPHA_SOFT STAT_ALPHA_HARD STAT_ALPHA_PROMOTE STAT_ALPHA_NONINF
export STAT_DELTA_SOFT STAT_DELTA_HARD STAT_DELTA_PROMOTE STAT_DELTA_HARMLESS
export STAT_ANCHOR_MIN_N STAT_ANCHOR_SCORE_KEEP STAT_ANCHOR_MIN_N_FALLBACK
export STAT_ANCHOR_MAX_AGE_GAMES STAT_PROMOTE_HOLDOUT_N STAT_TIEBREAK_ORDER

# --- 即死ゲーム分離 / 監視 (2026-08-20 新設, soren-stat-gate-design.md 参照) ---
#   実測根拠: eval 空間で明確な二峰性。谷 [2500,4000) は 17357 試合中 4 件(0.023%)。
#             即死は極端にバースト(平均連長比 9.5=ハーネス起因)、8/11 以降は 0.0%。
#   Phase 1 で INSTADEATH_SPLIT_ENABLED=1 にするまで update_rolling_scores 側は無変更。
INSTADEATH_SPLIT_ENABLED="${INSTADEATH_SPLIT_ENABLED:-0}"
DEAD_EVAL_THRESHOLD="${DEAD_EVAL_THRESHOLD:-3000}"
DEAD_RAW_THRESHOLD="${DEAD_RAW_THRESHOLD:-300}"
DEAD_MONITOR_FILE="${DEAD_MONITOR_FILE:-tmp/state/instadeath_monitor.json}"
DEAD_MONITOR_WINDOW="${DEAD_MONITOR_WINDOW:-400}"
DEAD_ALERT_WINDOW="${DEAD_ALERT_WINDOW:-50}"
DEAD_ALERT_RATE="${DEAD_ALERT_RATE:-0.10}"
DEAD_QUARANTINE_ENABLED="${DEAD_QUARANTINE_ENABLED:-1}"
DEAD_QUARANTINE_WINDOW="${DEAD_QUARANTINE_WINDOW:-20}"
DEAD_QUARANTINE_RATE="${DEAD_QUARANTINE_RATE:-0.30}"
DEAD_QUARANTINE_CLEAR_WINDOW="${DEAD_QUARANTINE_CLEAR_WINDOW:-20}"
DEAD_QUARANTINE_CLEAR_RATE="${DEAD_QUARANTINE_CLEAR_RATE:-0.05}"
DEAD_BURST_RATIO="${DEAD_BURST_RATIO:-3.0}"
DEAD_HARD_RATIO="${DEAD_HARD_RATIO:-0.5}"
# burst_ratio is blind in the p=0.85-0.99 band (2026-08-20 review round 2,
# issue 6); a near-total dead rate is independent evidence of a harness
# outage regardless of clustering.
DEAD_NEAR_TOTAL_RATE="${DEAD_NEAR_TOTAL_RATE:-0.90}"
DEAD_MAX_TURNS="${DEAD_MAX_TURNS:-3}"
DEAD_ALPHA="${DEAD_ALPHA:-0.01}"
DEAD_REGRESSION_ENABLED="${DEAD_REGRESSION_ENABLED:-0}"
# 実測で発見(Phase 1 実装レビュー, リスクR3): export が無いと python3 heredoc の
# os.environ.get() から見えず、config.sh の既定値を 1 に変えても機能がサイレント
# に no-op になる。この export 追加自体は毎試合の .env re-source と同じ経路
# (soren_loop.sh の再 source)で即反映され、worker 完全再起動は不要。
export INSTADEATH_SPLIT_ENABLED DEAD_EVAL_THRESHOLD DEAD_RAW_THRESHOLD
export DEAD_MONITOR_FILE DEAD_MONITOR_WINDOW DEAD_ALERT_WINDOW DEAD_ALERT_RATE
export DEAD_QUARANTINE_ENABLED DEAD_QUARANTINE_WINDOW DEAD_QUARANTINE_RATE
export DEAD_QUARANTINE_CLEAR_WINDOW DEAD_QUARANTINE_CLEAR_RATE
export DEAD_BURST_RATIO DEAD_HARD_RATIO DEAD_NEAR_TOTAL_RATE
export DEAD_MAX_TURNS DEAD_ALPHA DEAD_REGRESSION_ENABLED

# --- 探索速度の解放 (Phase 4, soren-stat-gate-design.md 参照) ---
IMPROVE_FUTILITY_RELEASE_ENABLED="${IMPROVE_FUTILITY_RELEASE_ENABLED:-0}"
IMPROVE_FUTILITY_MIN_GAMES="${IMPROVE_FUTILITY_MIN_GAMES:-32}"

# --- 帯域脱出機構 (D+E+F) ---
# D: 多様性プレミアム (anchor 選定時のメモリ内 selection_score のみに作用、永続化しない)
DIVERSITY_PREMIUM_ENABLED="${DIVERSITY_PREMIUM_ENABLED:-0}"
DIVERSITY_PREMIUM_WEIGHT="${DIVERSITY_PREMIUM_WEIGHT:-300}"
EXPLORE_GAP_MAX_RATIO="${EXPLORE_GAP_MAX_RATIO:-0.07}"
# E: 機械的 tabu (rollback された失敗 current の挙動近傍を一定期間 anchor 昇格不可に)
TABU_ENABLED="${TABU_ENABLED:-0}"
TABU_DISTANCE_THRESHOLD="${TABU_DISTANCE_THRESHOLD:-0.15}"
TABU_RETAIN="${TABU_RETAIN:-20}"
TABU_DECAY_GAMES="${TABU_DECAY_GAMES:-$((MIN_GAMES_BEFORE_IMPROVE * 8))}"
TABU_SIGNATURES_FILE="${TABU_SIGNATURES_FILE:-$TMP_STATE_DIR/tabu_signatures.jsonl}"
BEHAVIOR_SIGNATURES_FILE="${BEHAVIOR_SIGNATURES_FILE:-$TMP_STATE_DIR/behavior_signatures.json}"
HASH_HISTORY_INDEX_FILE="$TMP_STATE_DIR/hash_history_index.json"
LAST_ANCHOR_CHANGE_FILE="${LAST_ANCHOR_CHANGE_FILE:-$TMP_STATE_DIR/last_anchor_change.md}"
# F: wildcard パラメータ摂動 (連続 N サイクル無改善で AI を介さず数値定数を ±σ 摂動)
WILDCARD_ENABLED="${WILDCARD_ENABLED:-0}"
WILDCARD_TRIGGER_STAGNATION="${WILDCARD_TRIGGER_STAGNATION:-3}"
WILDCARD_EARLY_ESCAPE_LOCK_ENABLED="${WILDCARD_EARLY_ESCAPE_LOCK_ENABLED:-1}"
WILDCARD_EARLY_ESCAPE_MIN_GAMES="${WILDCARD_EARLY_ESCAPE_MIN_GAMES:-4}"
POST_REGRESSION_DIRECT_ESCAPE_ENABLED="${POST_REGRESSION_DIRECT_ESCAPE_ENABLED:-1}"
# counter 非依存トリガ: 回帰ストリークが閾値到達で WILDCARD 発火 (OK_BEAT マスク回避)。
# churn 緩和: rstreak 経路の連続発火を COOLDOWN 秒抑止 (cooldown マーカは improve.sh 所有)。
WILDCARD_REGRESSION_STREAK="${WILDCARD_REGRESSION_STREAK:-2}"
WILDCARD_STREAK_COOLDOWN_SEC="${WILDCARD_STREAK_COOLDOWN_SEC:-1800}"
WILDCARD_STREAK_COOLDOWN_FILE="$TMP_STATE_DIR/.wildcard_streak_cooldown"
WILDCARD_PARAM_COUNT_MIN="${WILDCARD_PARAM_COUNT_MIN:-1}"
WILDCARD_PARAM_COUNT_MAX="${WILDCARD_PARAM_COUNT_MAX:-3}"
WILDCARD_PERTURB_RATIO_MIN="${WILDCARD_PERTURB_RATIO_MIN:-0.20}"
WILDCARD_PERTURB_RATIO_MAX="${WILDCARD_PERTURB_RATIO_MAX:-0.40}"
WILDCARD_ADAPTIVE_SCALE_ENABLED="${WILDCARD_ADAPTIVE_SCALE_ENABLED:-1}"
WILDCARD_ADAPTIVE_SCALE_STEP="${WILDCARD_ADAPTIVE_SCALE_STEP:-0.25}"
WILDCARD_ADAPTIVE_SCALE_MAX="${WILDCARD_ADAPTIVE_SCALE_MAX:-2.00}"
WILDCARD_ADAPTIVE_EXTRA_PARAM_EVERY="${WILDCARD_ADAPTIVE_EXTRA_PARAM_EVERY:-2}"
WILDCARD_TABU_RECENT_LINES="${WILDCARD_TABU_RECENT_LINES:-12}"
WILDCARD_AI_ESCALATE_ENABLED="${WILDCARD_AI_ESCALATE_ENABLED:-1}"
WILDCARD_AI_ESCALATE_STREAK="${WILDCARD_AI_ESCALATE_STREAK:-3}"
WILDCARD_ESCAPE_AI_SEED_ENABLED="${WILDCARD_ESCAPE_AI_SEED_ENABLED:-1}"
WILDCARD_ESCAPE_AI_SEED_MIN_GAMES="${WILDCARD_ESCAPE_AI_SEED_MIN_GAMES:-4}"
WILDCARD_ESCAPE_AI_SEED_MIN_BEST_TYPE="${WILDCARD_ESCAPE_AI_SEED_MIN_BEST_TYPE:-14}"
WILDCARD_BANDIT_ENABLED="${WILDCARD_BANDIT_ENABLED:-1}"
WILDCARD_BANDIT_LOOKBACK="${WILDCARD_BANDIT_LOOKBACK:-80}"
WILDCARD_BANDIT_EXPLORE_RATE="${WILDCARD_BANDIT_EXPLORE_RATE:-0.35}"
WILDCARD_PATIENCE_GAMES="${WILDCARD_PATIENCE_GAMES:-12}"
WILDCARD_PARALLEL_ENABLED="${WILDCARD_PARALLEL_ENABLED:-1}"
WILDCARD_PARALLEL_JOBS="${WILDCARD_PARALLEL_JOBS:-6}"
WILDCARD_PARALLEL_GAMES="${WILDCARD_PARALLEL_GAMES:-6}"
POST_IMPROVE_PARAM_PARALLEL_ENABLED="${POST_IMPROVE_PARAM_PARALLEL_ENABLED:-0}"
POST_IMPROVE_PARAM_PARALLEL_JOBS="${POST_IMPROVE_PARAM_PARALLEL_JOBS:-6}"
POST_IMPROVE_PARAM_PARALLEL_STOP_SOREN91="${POST_IMPROVE_PARAM_PARALLEL_STOP_SOREN91:-0}"
POST_IMPROVE_PARAM_PARALLEL_SERVE_BASE_PORT="${POST_IMPROVE_PARAM_PARALLEL_SERVE_BASE_PORT:-18180}"
POST_IMPROVE_PARAM_PARALLEL_CDP_BASE_PORT="${POST_IMPROVE_PARAM_PARALLEL_CDP_BASE_PORT:-19320}"
WILDCARD_PARALLEL_CULL_AFTER_GAMES="${WILDCARD_PARALLEL_CULL_AFTER_GAMES:-1}"
WILDCARD_PARALLEL_CULL_LEADER_MIN_GAMES="${WILDCARD_PARALLEL_CULL_LEADER_MIN_GAMES:-2}"
WILDCARD_PARALLEL_CULL_COMP_RATIO="${WILDCARD_PARALLEL_CULL_COMP_RATIO:-0.90}"
WILDCARD_PARALLEL_LINGERING_SLOT_MAX_CULLS="${WILDCARD_PARALLEL_LINGERING_SLOT_MAX_CULLS:-0}"
# Russia-rate objective guard (2026-05-30): choose_winner refuses to adopt a non-Russia
# winner over a baseline that is PROVEN Russia-capable (>= MIN_COUNT historical Russia
# foundings, read from current_strategy_run.json) unless the winner's composite gain is
# >= OVERRIDE_RATIO (large enough to be worth losing Russia capability). Prevents the
# 07:12-style regression where ~6-game sampling can't see a rare Russia and tunes it
# away for raw score. MIN_COUNT=1 (default) protects any strategy that has demonstrated
# Russia capability — strategies rarely accumulate 2 Russias before turnover, so a higher
# threshold makes the guard inert. The 2026-05-25 single-Russia 固着 is avoided by the
# soft OVERRIDE_RATIO escape (that prior protection had none), NOT by MIN_COUNT. Raise
# MIN_COUNT to 2 (or OVERRIDE_RATIO) if score progress stalls. Exported so the
# wildcard_parallel.py subprocess sees them via os.getenv.
export WILDCARD_PARALLEL_RUSSIA_GUARD_MIN_COUNT="${WILDCARD_PARALLEL_RUSSIA_GUARD_MIN_COUNT:-1}"
export WILDCARD_PARALLEL_RUSSIA_GUARD_OVERRIDE_RATIO="${WILDCARD_PARALLEL_RUSSIA_GUARD_OVERRIDE_RATIO:-1.15}"
# Russia cull protection + adoption recurrence (2026-05-31, user request). Two coordinated
# knobs that fix "Russia-founding SLOTS got culled":
#   CULL_PROTECT_RUSSIA=1 (default ON, the requested fix): should_cull never comp-culls a
#     candidate with russia_count>=1, so a rare upper-tail Russia (whose median comp is
#     routinely below the leader threshold) is not killed by cull_after_games=1 before it
#     can prove recurrence / reach choose_winner / be recorded. Bounded by --max-runtime-sec.
#   ADOPT_RUSSIA_RECURRENCE=1 (default ON, 05-25-safe): choose_winner's leading objective
#     bit requires RECURRENT Russia (russia_count>=RECURRENCE_MIN_COUNT OR a reproduced
#     2nd-Russia frontier over >=FRONTIER_MIN_GAMES boards: T15x2 OR T15x1+T14x2), so a WEAK
#     single lucky Russia does NOT lexicographically beat a higher-comp non-Russia (the
#     2026-05-25 固着 trap). A single Russia may still win only on comp/p25 (escape valve).
#   Thresholds mirror eloop_improve.sh (russia>=2) and regression.sh OBJECTIVE_FRONTIER_MIN_GAMES=2.
# Set either to 0 to disable. Exported so the wildcard_parallel.py subprocess sees them.
export WILDCARD_PARALLEL_CULL_PROTECT_RUSSIA="${WILDCARD_PARALLEL_CULL_PROTECT_RUSSIA:-1}"
export WILDCARD_PARALLEL_ADOPT_RUSSIA_RECURRENCE="${WILDCARD_PARALLEL_ADOPT_RUSSIA_RECURRENCE:-1}"
export WILDCARD_PARALLEL_RUSSIA_RECURRENCE_MIN_COUNT="${WILDCARD_PARALLEL_RUSSIA_RECURRENCE_MIN_COUNT:-2}"
export WILDCARD_PARALLEL_RUSSIA_FRONTIER_MIN_GAMES="${WILDCARD_PARALLEL_RUSSIA_FRONTIER_MIN_GAMES:-2}"
# Cull anchor (2026-05-30, user request): "leader" culls candidates below cull_comp_ratio
# of the STRONGEST survivor (harder culling → wider exploration via regeneration);
# "baseline" culls only against the current strategy (prior behavior, narrower search).
# On the --max-runtime-sec timeout the best-so-far candidate (>= INTERRUPTED_MIN_GAMES
# games, still beating the baseline) is adopted instead of discarding the run.
export WILDCARD_PARALLEL_CULL_ANCHOR="${WILDCARD_PARALLEL_CULL_ANCHOR:-leader}"
export WILDCARD_PARALLEL_INTERRUPTED_MIN_GAMES="${WILDCARD_PARALLEL_INTERRUPTED_MIN_GAMES:-2}"
# Per-candidate-game timeout (2026-05-30): raised 420→1200s. Good strategies merge well,
# play more turns, and run LONGER, so a 7-min timeout was killing the BEST candidates
# (timed out → accepted with <min_successful_games → ineligible to win → slot wasted).
# 20 min lets long high-type games finish. Bounded overall by --max-runtime-sec.
export WILDCARD_PARALLEL_GAME_TIMEOUT="${WILDCARD_PARALLEL_GAME_TIMEOUT:-1200}"
WILDCARD_PARALLEL_EVALUATE_MODE="${WILDCARD_PARALLEL_EVALUATE_MODE:-real}"
WILDCARD_PARALLEL_CDP_BASE_PORT="${WILDCARD_PARALLEL_CDP_BASE_PORT:-19320}"
WILDCARD_PARALLEL_BRIDGE_TIMEOUT="${WILDCARD_PARALLEL_BRIDGE_TIMEOUT:-45}"
WILDCARD_PARALLEL_MIN_SUCCESSFUL_GAMES="${WILDCARD_PARALLEL_MIN_SUCCESSFUL_GAMES:-0}"
WILDCARD_PARALLEL_BGM_VOLUME="${WILDCARD_PARALLEL_BGM_VOLUME:-0}"
WILDCARD_PARALLEL_SE_VOLUME="${WILDCARD_PARALLEL_SE_VOLUME:-1.5}"
WILDCARD_PARALLEL_WORK_DIR="$TMP_STATE_DIR/../wildcard_parallel"
WILDCARD_PARALLEL_STATUS_FILE="$TMP_STATE_DIR/wildcard_parallel_status.json"
WILDCARD_PARALLEL_HTML_FILE="$TMP_STATE_DIR/wildcard_parallel_overlay.html"
WILDCARD_PARALLEL_OVERLAY_SOURCE="${OBS_WILDCARD_PARALLEL_OVERLAY_SOURCE:-wildcardParallelOverlay}"
WILDCARD_PARALLEL_OVERLAY_WIDTH="${WILDCARD_PARALLEL_OVERLAY_WIDTH:-1920}"
# Overlay browser source renders the full 1920x1080 canvas. The HTML draws an
# opaque compact strip at the top (height STRIP_H) and is transparent below it,
# so the higher-layer candidate window tiles below the strip are never hidden.
WILDCARD_PARALLEL_OVERLAY_HEIGHT="${WILDCARD_PARALLEL_OVERLAY_HEIGHT:-1080}"
WILDCARD_PARALLEL_OVERLAY_STRIP_H="${WILDCARD_PARALLEL_OVERLAY_STRIP_H:-200}"
# Candidate game-window tiles: 3 cols x 2 rows filling y=[STRIP_H,1080], x=[0,1920].
# 3*640=1920 wide; 200 + 2*440 = 1080 tall (bottom row ends exactly at 1080).
WILDCARD_PARALLEL_OBS_CANDIDATE_COLS="${WILDCARD_PARALLEL_OBS_CANDIDATE_COLS:-3}"
WILDCARD_PARALLEL_OBS_CANDIDATE_W="${WILDCARD_PARALLEL_OBS_CANDIDATE_W:-640}"
WILDCARD_PARALLEL_OBS_CANDIDATE_H="${WILDCARD_PARALLEL_OBS_CANDIDATE_H:-440}"
WILDCARD_PARALLEL_OBS_CANDIDATE_X="${WILDCARD_PARALLEL_OBS_CANDIDATE_X:-0}"
WILDCARD_PARALLEL_OBS_CANDIDATE_Y="${WILDCARD_PARALLEL_OBS_CANDIDATE_Y:-200}"
WILDCARD_PARALLEL_OBS_CANDIDATE_COL_STRIDE="${WILDCARD_PARALLEL_OBS_CANDIDATE_COL_STRIDE:-640}"
WILDCARD_PARALLEL_OBS_CANDIDATE_ROW_STRIDE="${WILDCARD_PARALLEL_OBS_CANDIDATE_ROW_STRIDE:-440}"
ARCHIVE_RESTART_ENABLED="${ARCHIVE_RESTART_ENABLED:-1}"
ARCHIVE_RESTART_STREAK="${ARCHIVE_RESTART_STREAK:-3}"
ARCHIVE_RESTART_MIN_COMP_RATIO="${ARCHIVE_RESTART_MIN_COMP_RATIO:-0.92}"
ARCHIVE_RESTART_MIN_BEST_TYPE="${ARCHIVE_RESTART_MIN_BEST_TYPE:-14}"
ARCHIVE_RESTART_MIN_RUSSIA_COUNT="${ARCHIVE_RESTART_MIN_RUSSIA_COUNT:-2}"
ARCHIVE_RESTART_MIN_RUSSIA_RATE="${ARCHIVE_RESTART_MIN_RUSSIA_RATE:-0.15}"
ARCHIVE_RESTART_FRONTIER_MIN_BEST_TYPE="${ARCHIVE_RESTART_FRONTIER_MIN_BEST_TYPE:-15}"
ARCHIVE_RESTART_OBJECTIVE_FAIL_PERMANENT="${ARCHIVE_RESTART_OBJECTIVE_FAIL_PERMANENT:-1}"
ARCHIVE_RESTART_MAX_CANDIDATES="${ARCHIVE_RESTART_MAX_CANDIDATES:-24}"
ARCHIVE_RESTART_PATIENCE_GAMES="${ARCHIVE_RESTART_PATIENCE_GAMES:-12}"
ARCHIVE_RESTART_INCLUDE_PERMANENT="${ARCHIVE_RESTART_INCLUDE_PERMANENT:-1}"
ARCHIVE_RESTART_ALLOW_ORIGIN_RETRY="${ARCHIVE_RESTART_ALLOW_ORIGIN_RETRY:-1}"
ARCHIVE_RESTART_COOLDOWN_FILE="$TMP_STATE_DIR/archive_restart_cooldown.json"
ARCHIVE_RESTART_COOLDOWN_SEC="${ARCHIVE_RESTART_COOLDOWN_SEC:-21600}"
ARCHIVE_RESTART_NO_CANDIDATE_COOLDOWN_FILE="$TMP_STATE_DIR/.archive_restart_no_candidate"
ARCHIVE_RESTART_NO_CANDIDATE_COOLDOWN_SEC="${ARCHIVE_RESTART_NO_CANDIDATE_COOLDOWN_SEC:-900}"
ANNEALING_OBSERVE_ENABLED="${ANNEALING_OBSERVE_ENABLED:-1}"
ANNEALING_BASE_TEMP="${ANNEALING_BASE_TEMP:-1800}"
ANNEALING_DECAY="${ANNEALING_DECAY:-0.85}"
STAGNATION_COUNTER_FILE="$TMP_STATE_DIR/stagnation_counter.json"
WILDCARD_ORIGIN_FILE="$TMP_STATE_DIR/wildcard_origin.json"
WILDCARD_ATTEMPT_STATE_FILE="$TMP_STATE_DIR/wildcard_attempt_state.json"
WILDCARD_OUTCOME_FILE="$TMP_STATE_DIR/wildcard_outcomes.jsonl"
ANNEALING_OBSERVE_FILE="$TMP_STATE_DIR/annealing_candidates.jsonl"
WILDCARD_PROGRESS_AUDIO_ENABLED="${WILDCARD_PROGRESS_AUDIO_ENABLED:-1}"
WILDCARD_PROGRESS_AUDIO_STATE_FILE="$TMP_STATE_DIR/wildcard_progress_audio_last.json"
WILDCARD_PROGRESS_AUDIO_MILESTONES="${WILDCARD_PROGRESS_AUDIO_MILESTONES:-1,3,6,9,12}"
WILDCARD_PROGRESS_AUDIO_MIN_DELTA="${WILDCARD_PROGRESS_AUDIO_MIN_DELTA:-0}"
MONITOR_REPORT_AUDIO_ENABLED="${MONITOR_REPORT_AUDIO_ENABLED:-1}"
MONITOR_REPORT_AUDIO_STATE_FILE="$TMP_STATE_DIR/monitor_report_audio_last.json"
MONITOR_REPORT_STATUS_FILE="${MONITOR_REPORT_STATUS_FILE:-$TMP_STATE_DIR/monitor_report_status.json}"
MONITOR_REPORT_STALE_SEC="${MONITOR_REPORT_STALE_SEC:-900}"
MONITOR_REPORT_OLD_SEC="${MONITOR_REPORT_OLD_SEC:-3600}"
MONITOR_REPORT_AUDIO_MIN_INTERVAL_SEC="${MONITOR_REPORT_AUDIO_MIN_INTERVAL_SEC:-900}"
MONITOR_REPORT_IMPROVE_GUARD_ENABLED="${MONITOR_REPORT_IMPROVE_GUARD_ENABLED:-0}"
MONITOR_REPORT_IMPROVE_GUARD_MAX_AGE="${MONITOR_REPORT_IMPROVE_GUARD_MAX_AGE:-3600}"
IMPROVE_STRUCTURAL_ERROR_MAX_CONTINUES="${IMPROVE_STRUCTURAL_ERROR_MAX_CONTINUES:-2}"
VIEWER_CHAT_MONITOR_FILE="${VIEWER_CHAT_MONITOR_FILE:-$ELOOP_LIB_DIR/$TMP_STATE_DIR/viewer_chat_monitor.json}"
COMMENT_CONTEXT_HISTORY_FILE="${COMMENT_CONTEXT_HISTORY_FILE:-$ELOOP_LIB_DIR/tmp/.viewer_chat/comment_context_history.log}"
VIEWER_CHAT_MONITOR_SOURCE="${VIEWER_CHAT_MONITOR_SOURCE:-$COMMENT_CONTEXT_HISTORY_FILE}"
VIEWER_CHAT_MONITOR_LOOKBACK="${VIEWER_CHAT_MONITOR_LOOKBACK:-200}"
CURRENT_RUN_AUTO_REPAIR_ENABLED="${CURRENT_RUN_AUTO_REPAIR_ENABLED:-1}"
CURRENT_RUN_AUTO_REPAIR_LIMIT="${CURRENT_RUN_AUTO_REPAIR_LIMIT:-12}"

# Dashboard OBS visibility 制御
# プレイ中は dashboard ソースを hide、GAMEOVER 時に show する。meriken AI と同じパターン
OBS_DASHBOARD_VISIBILITY_ENABLED="${OBS_DASHBOARD_VISIBILITY_ENABLED:-1}"
OBS_DASHBOARD_SCENE="${OBS_DASHBOARD_SCENE:-soren}"
OBS_DASHBOARD_SOURCE="${OBS_DASHBOARD_SOURCE:-dashboard}"
DASHBOARD_GAMEOVER_HOLD_SEC="${DASHBOARD_GAMEOVER_HOLD_SEC:-3}"

STRATEGY_HASH_ARCHIVE_DIR="strategy_versions/by_hash"
# 永続アーカイブ: prune されないバックアップ。backfill のフォールバック元
STRATEGY_HASH_PERMANENT_ARCHIVE_DIR="strategy_versions_archive/by_hash"
# 旧設定の keep_top=10 が親シェルに残っていても、既定値は 100 に引き上げる。
case "${HASH_ARCHIVE_KEEP_TOP:-}" in
"" | 10) HASH_ARCHIVE_KEEP_TOP=100 ;;
esac
case "${HASH_ARCHIVE_PRUNE_SAFETY_MIN_KEEP:-}" in
"" | *[!0-9]*) HASH_ARCHIVE_PRUNE_SAFETY_MIN_KEEP=20 ;;
esac
[ "$HASH_ARCHIVE_PRUNE_SAFETY_MIN_KEEP" -lt 1 ] && HASH_ARCHIVE_PRUNE_SAFETY_MIN_KEEP=1
case "${HASH_ARCHIVE_PRUNE_SAFETY_MIN_RATIO_PCT:-}" in
"" | *[!0-9]*) HASH_ARCHIVE_PRUNE_SAFETY_MIN_RATIO_PCT=60 ;;
esac
[ "$HASH_ARCHIVE_PRUNE_SAFETY_MIN_RATIO_PCT" -lt 1 ] && HASH_ARCHIVE_PRUNE_SAFETY_MIN_RATIO_PCT=1
[ "$HASH_ARCHIVE_PRUNE_SAFETY_MIN_RATIO_PCT" -gt 100 ] && HASH_ARCHIVE_PRUNE_SAFETY_MIN_RATIO_PCT=100
HASH_ARCHIVE_RESTORE_PERMANENT="${HASH_ARCHIVE_RESTORE_PERMANENT:-0}"
HASH_ARCHIVE_PRUNE_BACKGROUND="${HASH_ARCHIVE_PRUNE_BACKGROUND:-1}"
COMMENT_QUEUE_DIR="tmp/.comment_queue"
COMMENT_SPOKEN_HISTORY_DIR="tmp/.comment_queue/spoken_history"
COMMENT_SPOKEN_HISTORY_MAX_FILES="${COMMENT_SPOKEN_HISTORY_MAX_FILES:-16}"
COMMENT_SPOKEN_PROMPT_ITEMS="${COMMENT_SPOKEN_PROMPT_ITEMS:-8}"
COMMENT_SPOKEN_PROMPT_MAX_CHARS="${COMMENT_SPOKEN_PROMPT_MAX_CHARS:-2500}"
COMMENT_SPOKEN_ITEM_MAX_CHARS="${COMMENT_SPOKEN_ITEM_MAX_CHARS:-350}"
RUSSIA_CELEBRATION_WORKER_PID_FILE="$TMP_STATE_DIR/.russia_celebration_worker.pid"
COMMENT_WATCHER_PID_FILE="tmp/.comment_queue/watcher.pid"
COMMENT_WATCHER_INTERVAL="${COMMENT_WATCHER_INTERVAL:-2}"
COMMENT_WORKER_HEALTH_TTL=30
COMMENT_PLAYER_HEARTBEAT_FILE="tmp/.comment_queue/player.heartbeat"
COMMENT_WATCHER_HEARTBEAT_FILE="tmp/.comment_queue/watcher.heartbeat"
COMMENT_BATCH_HISTORY_FILE="tmp/.comment_queue/processed_batch_hashes.log"
COMMENT_BATCH_INFLIGHT_FILE="tmp/.comment_queue/inflight_batch.log"
COMMENT_BATCH_DEDUP_TTL=900
COMMENT_PROCESSED_LINES_FILE="tmp/.comment_queue/processed_line_hashes.log"
COMMENT_PROCESSED_LINES_TTL=1800
COMMENT_PROCESSED_LINES_MAX=500
RADIO_DEFERRED_QUEUE_MAX="${RADIO_DEFERRED_QUEUE_MAX:-5}"
COMMENT_FAILURE_BACKOFF_SEC="${COMMENT_FAILURE_BACKOFF_SEC:-${AI_AGENT_BACKOFF_SEC:-600}}"
COMMENT_FAILURE_BACKOFF_FILE="${COMMENT_FAILURE_BACKOFF_FILE:-$TMP_STATE_DIR/comment_generation_backoff_until}"
SOREN91_LAST_COMMENTED_GAME_FILE="$COMMENT_QUEUE_DIR/soren91_last_commented_game"
SOREN91_GAME_COMMENTARY_INTERVAL=60
RADIO_DEFERRED_QUEUE_DIR="tmp/.radio_deferred_queue"
OUTBOUND_CHAT_QUEUE_DIR="tmp/.outbound_chat_queue"
OUTBOUND_CHAT_PENDING_DIR="$OUTBOUND_CHAT_QUEUE_DIR/pending"
OUTBOUND_CHAT_SENT_DIR="$OUTBOUND_CHAT_QUEUE_DIR/sent"
MANUAL_AUDIO_TRIGGER_DIR="tmp/.manual_audio_triggers"
MANUAL_AUDIO_TRIGGER_MAX_PER_TICK=3
RUSSIA_CELEBRATION_CLIP_DELAY_SEC="${RUSSIA_CELEBRATION_CLIP_DELAY_SEC:-5}"
SOVIET_CELEBRATION_CLIP_DELAY_SEC="${SOVIET_CELEBRATION_CLIP_DELAY_SEC:-20}"
# --- Twitch 広告スヌーズ（読み上げ中、GitHub #18） ---
TWITCH_ADS_ENABLED="${TWITCH_ADS_ENABLED:-1}"
TWITCH_SNOOZE_THRESHOLD_SEC="${TWITCH_SNOOZE_THRESHOLD_SEC:-600}"
TWITCH_SNOOZE_POLL_SEC="${TWITCH_SNOOZE_POLL_SEC:-240}"
TWITCH_ADS_DEBUG_LOG="${TWITCH_ADS_DEBUG_LOG:-tmp/debug/twitch_ads.log}"
SPEAKING_STATE_FILE="${SPEAKING_STATE_FILE:-tmp/state/speaking.json}"
SPEAKING_GRACE_SEC="${SPEAKING_GRACE_SEC:-3}"
# --- ラジオ原稿アーカイブ (soviet_now#113 / docich#10) ---
# 再生完了原稿 (backups/radio_scripts/<YYYYMMDD>/*.txt + .history + .meta.json) を
# VM 外へ退避する。Git 鏡 (private) と Object Storage (rclone) のハイブリッド。
# テキストのみ退避 (WAV/MP3は容量のため再合成で代替)。WAV が必要な日だけ手動退避。
RADIO_ARCHIVE_ENABLED="${RADIO_ARCHIVE_ENABLED:-1}"
RADIO_ARCHIVE_GIT_ENABLED="${RADIO_ARCHIVE_GIT_ENABLED:-1}"
RADIO_ARCHIVE_GIT_REPO="${RADIO_ARCHIVE_GIT_REPO:-}" # 例: git@github.com:azumag/soren-radio-archive.git (空ならスキップ)
RADIO_ARCHIVE_GIT_BRANCH="${RADIO_ARCHIVE_GIT_BRANCH:-main}"
RADIO_ARCHIVE_GIT_DIR="${RADIO_ARCHIVE_GIT_DIR:-tmp/radio_archive_mirror}" # 一時clone先
RADIO_ARCHIVE_RCLONE_ENABLED="${RADIO_ARCHIVE_RCLONE_ENABLED:-0}"
RADIO_ARCHIVE_RCLONE_REMOTE="${RADIO_ARCHIVE_RCLONE_REMOTE:-}" # 例: oci:soren-radio-archive
RADIO_ARCHIVE_RCLONE_BUCKET="${RADIO_ARCHIVE_RCLONE_BUCKET:-soren-radio-archive}"
RADIO_ARCHIVE_PUSH_HOUR_JST="${RADIO_ARCHIVE_PUSH_HOUR_JST:-04:00}"
RADIO_ARCHIVE_RETENTION_DAYS="${RADIO_ARCHIVE_RETENTION_DAYS:-90}" # Git鏡は90日、それ以前は月次タグへsquash (将来)
RADIO_ARCHIVE_STATE_FILE="${RADIO_ARCHIVE_STATE_FILE:-$TMP_STATE_DIR/radio_archive_pushed.json}"
RADIO_ARCHIVE_DRY_RUN="${RADIO_ARCHIVE_DRY_RUN:-0}"
export RADIO_ARCHIVE_ENABLED RADIO_ARCHIVE_GIT_ENABLED RADIO_ARCHIVE_GIT_REPO RADIO_ARCHIVE_GIT_BRANCH RADIO_ARCHIVE_GIT_DIR
export RADIO_ARCHIVE_RCLONE_ENABLED RADIO_ARCHIVE_RCLONE_REMOTE RADIO_ARCHIVE_RCLONE_BUCKET RADIO_ARCHIVE_PUSH_HOUR_JST
export RADIO_ARCHIVE_RETENTION_DAYS RADIO_ARCHIVE_STATE_FILE RADIO_ARCHIVE_DRY_RUN

# --- ポッドキャスト (docich#10) ---
PODCAST_ENABLED="${PODCAST_ENABLED:-1}"
PODCAST_OUTPUT_DIR="${PODCAST_OUTPUT_DIR:-output/podcast}"
PODCAST_VOICE="${PODCAST_VOICE:-109}" # 東北イタコ
PODCAST_BASE_URL="${PODCAST_BASE_URL:-https://example.com/podcast}"
PODCAST_RCLONE_ENABLED="${PODCAST_RCLONE_ENABLED:-0}"
PODCAST_RCLONE_REMOTE="${PODCAST_RCLONE_REMOTE:-}"
PODCAST_RCLONE_BUCKET="${PODCAST_RCLONE_BUCKET:-soren-radio-archive}"
PODCAST_RCLONE_PREFIX="${PODCAST_RCLONE_PREFIX:-podcast}"
# 生成は Mac 側 launchd (com.azumag.soren-podcast.build, 04:30 JST) が担当する。
# VM の podcast.timer は VOICEVOX を配信本体と奪い合って失敗し続けたため 2026-08-26 に disable 済み。
# 本値はドキュメント用でスケジューラからは読まれない (変更に worker 再起動は不要)。
PODCAST_BUILD_HOUR_JST="${PODCAST_BUILD_HOUR_JST:-04:30}"
# 生成物の保持日数。動画 1 本が 300MB 前後 (2026-08-25 分の実測 299MB) あり毎日積むと月 9GB に
# なるため、tools/podcast_gc.sh が日次パイプラインの先頭で古い mp4 を消す。
# 未公開 (publish.json 無し) の回は PODCAST_GC_UNPUBLISHED_DAYS (既定 7) まで残す。
# 対象拡張子は PODCAST_GC_SUFFIXES (既定 ".mp4"; mp3 も消すなら ".mp4 .mp3")。
# 本値は Mac 側スクリプトが環境変数として読む (VM の worker からは参照されない)。
PODCAST_RETENTION_DAYS="${PODCAST_RETENTION_DAYS:-3}"
# YouTube 公開後に Bluesky へ告知する (tools/bluesky_post.py)。
# 認証は ~/.config/soren/bluesky.json か BLUESKY_HANDLE/BLUESKY_APP_PASSWORD。
# 認証情報が無ければ日次パイプラインは黙って [4/4] を飛ばす (fail-open)。
# 鍵はリポジトリにも .env にも書かない (AGENTS.md)。
PODCAST_BLUESKY_ENABLED="${PODCAST_BLUESKY_ENABLED:-1}"
PODCAST_BLUESKY_TAGS="${PODCAST_BLUESKY_TAGS:-}"   # 例: "ニュース,ポッドキャスト"
export PODCAST_ENABLED PODCAST_OUTPUT_DIR PODCAST_VOICE PODCAST_BASE_URL PODCAST_RETENTION_DAYS
export PODCAST_BLUESKY_ENABLED PODCAST_BLUESKY_TAGS
# 編成 (compose): 1日分の原稿をそのまま連結すると 3〜5 時間の朗読になるため
# (実測: 08-19〜08-25 の 7 日で 2h43m〜5h24m、平均 4h。1 本平均 1264 字 = 約 4 分)、
# LLM で「その日の話題を 1 本の番組へ編成し直す」段を挟む (docich#10)。
# 編成の長さ。0 = 自動 (その日の話題を全部拾う)。数値を入れるとその字数へ絞る。
# VOICEVOX 実測 306 字/分 なので、3500字≒11分 / 20000字≒65分 / 55000字≒3時間。
# 参考(市場調査): デイリーニュース番組の推奨帯は 8〜15 分、合成音声は 12 分前後で聴取疲労。
PODCAST_TARGET_CHARS="${PODCAST_TARGET_CHARS:-0}"
PODCAST_SECTION_CHARS="${PODCAST_SECTION_CHARS:-1800}"             # 1 コーナーの目標字数 (約6分)
PODCAST_TOPICS_PER_SECTION="${PODCAST_TOPICS_PER_SECTION:-5}"      # 自動時に 1 コーナーへ入れる話題数
PODCAST_SOURCE_CHAR_BUDGET="${PODCAST_SOURCE_CHAR_BUDGET:-200000}" # 要約段へ渡す上限字数 (1日分は約7万字)
# 生成経路 (ユーザー指定: codex + gpt luna)
PODCAST_LLM_BIN="${PODCAST_LLM_BIN:-codex}"
PODCAST_LLM_MODEL="${PODCAST_LLM_MODEL:-gpt-5.6-luna}"
PODCAST_LLM_TIMEOUT="${PODCAST_LLM_TIMEOUT:-900}"
PODCAST_LLM_WORKERS="${PODCAST_LLM_WORKERS:-3}"
# 要約 (map) 段: 素材を 1 発で投げると API の時間上限に達する (旧経路で 59,909 字が 15 分タイムアウト)
PODCAST_DIGEST_BATCH="${PODCAST_DIGEST_BATCH:-8}"
PODCAST_DIGEST_TIMEOUT="${PODCAST_DIGEST_TIMEOUT:-600}"
export PODCAST_TARGET_CHARS PODCAST_SECTION_CHARS PODCAST_TOPICS_PER_SECTION PODCAST_SOURCE_CHAR_BUDGET
export PODCAST_LLM_BIN PODCAST_LLM_MODEL PODCAST_LLM_TIMEOUT PODCAST_LLM_WORKERS
export PODCAST_DIGEST_BATCH PODCAST_DIGEST_TIMEOUT
export PODCAST_RCLONE_ENABLED PODCAST_RCLONE_REMOTE PODCAST_RCLONE_BUCKET PODCAST_RCLONE_PREFIX PODCAST_BUILD_HOUR_JST

# --- VOICEVOX 合成ロック / 前景優先待ち（sayキュー詰まりのデッドロック対策） ---
# 背景ラジオは前景音声（コメント等）が来たら譲るが、無期限待ちはデッドロックする
# ため有限化する。前景 180s に対し背景は短め(90/60)にし、競合時は前景が勝つ非対称にする。
VOICEVOX_SYNTH_LOCK_STALE_SEC="${VOICEVOX_SYNTH_LOCK_STALE_SEC:-180}"
VOICEVOX_SYNTH_LOCK_DEAD_GRACE_SEC="${VOICEVOX_SYNTH_LOCK_DEAD_GRACE_SEC:-10}"
VOICEVOX_SYNTH_LOCK_HUNG_SEC="${VOICEVOX_SYNTH_LOCK_HUNG_SEC:-60}"
VOICEVOX_SYNTH_PRIORITY_WAIT_STALE_SEC="${VOICEVOX_SYNTH_PRIORITY_WAIT_STALE_SEC:-60}"
VOICEVOX_RADIO_PRIORITY_WAIT_SEC="${VOICEVOX_RADIO_PRIORITY_WAIT_SEC:-90}"
VOICEVOX_RADIO_LOCK_WAIT_SEC="${VOICEVOX_RADIO_LOCK_WAIT_SEC:-60}"
export VOICEVOX_SYNTH_LOCK_STALE_SEC VOICEVOX_SYNTH_LOCK_DEAD_GRACE_SEC VOICEVOX_SYNTH_LOCK_HUNG_SEC
export VOICEVOX_SYNTH_PRIORITY_WAIT_STALE_SEC VOICEVOX_RADIO_PRIORITY_WAIT_SEC VOICEVOX_RADIO_LOCK_WAIT_SEC

# VM 読み上げキュー連携（作業中バナー）
COMMENT_AUDIO_DEDUP_TTL_SEC="${COMMENT_AUDIO_DEDUP_TTL_SEC:-120}"
mkdir -p "$STRATEGY_VERSIONS_DIR" "$STRATEGY_HASH_ARCHIVE_DIR" "$STRATEGY_HASH_PERMANENT_ARCHIVE_DIR" "$HISTORY_DIR" \
	"$TMP_STATE_DIR" "$TMP_MARKERS_DIR" "$TMP_HISTORY_DIR" "$TMP_DEBUG_DIR" "$TMP_CACHE_DIR" \
	"$COMMENT_QUEUE_DIR" "$COMMENT_SPOKEN_HISTORY_DIR" "$RADIO_DEFERRED_QUEUE_DIR" \
	"$MANUAL_AUDIO_TRIGGER_DIR" "$RADIO_WEB_GROUNDING_CACHE_DIR" \
	"$OUTBOUND_CHAT_PENDING_DIR" "$OUTBOUND_CHAT_SENT_DIR" \
	"tmp/.twitch_chat" "tmp/.youtube_chat" "tmp/.kick_chat" "tmp/.viewer_chat"

if [ -f "tmp/advice.md" ] && [ ! -f "$MAIN_STRATEGY_ADVICE_FILE" ]; then
	mv "tmp/advice.md" "$MAIN_STRATEGY_ADVICE_FILE" 2>/dev/null || cp "tmp/advice.md" "$MAIN_STRATEGY_ADVICE_FILE" 2>/dev/null || true
fi

# 探索モード固定化: explore.sh が作成するマーカを再アサートする。
# soren_loop.sh が毎周回 .env を再読込しても EXPLORE_MODE=1 が剥がれないようにする。
if [ -f "$ELOOP_LIB_DIR/tmp/state/explore_mode" ]; then
	EXPLORE_MODE=1
	STREAMING_ENABLED=0
	export EXPLORE_MODE STREAMING_ENABLED
fi

# --- tmp/ レイアウト移行 (旧パス → 新サブディレクトリ) ---
if [ ! -f "$TMP_STATE_DIR/.migrated" ]; then
	# state files
	for f in improve_state.json accumulated_games.json rolling_scores.json \
		rejected_hash_metrics.json rollback_target_cooldown.json best_strategy_anchor.json active_branch.json last_rollback_pair.json .russia_celebration_worker.pid \
		.radio_state .comment_gen_state radio_talk_played .news_last_success.txt \
		.status_fullscreen_last .news_shown_lines.txt .news_shown_mtime.txt; do
		[ -f "tmp/$f" ] && mv "tmp/$f" "$TMP_STATE_DIR/$f" 2>/dev/null
	done
	# markers
	for f in tmp/.radio_done_* tmp/.radio_inflight_* tmp/.timed_corner_done_* tmp/.timed_corner_inflight_*; do
		[ -e "$f" ] && mv "$f" "$TMP_MARKERS_DIR/" 2>/dev/null
	done
	for f in .russia_created .soviet_created; do
		[ -f "tmp/$f" ] && mv "tmp/$f" "$TMP_MARKERS_DIR/$f" 2>/dev/null
	done
	# history
	for f in .past_radio_themes.txt past_radio_topics.txt past_news_read.txt \
		past_radio_theme_bodies.txt past_news_read_keys.txt past_news_topic_keys.txt past_news_read_sources.txt rejected_hashes.txt \
		.past_news_titles.txt .past_news_links.txt russia_creation_history.tsv soviet_creation_history.tsv; do
		[ -f "tmp/$f" ] && mv "tmp/$f" "$TMP_HISTORY_DIR/$f" 2>/dev/null
	done
	# debug
	for f in tmp/radio_short_*.txt tmp/radio_factcheck_failed_*.txt tmp/radio_russia_celebration.txt; do
		[ -e "$f" ] && mv "$f" "$TMP_DEBUG_DIR/" 2>/dev/null
	done
	[ -f "tmp/improve_ai.log" ] && mv "tmp/improve_ai.log" "$TMP_DEBUG_DIR/improve_ai.log" 2>/dev/null
	touch "$TMP_STATE_DIR/.migrated"
fi
