[Unit]
After=soren-runtime.service

[Service]
Environment=HOME=/home/ubuntu
ExecCondition=/home/ubuntu/soren/stream_backend_condition.sh obs
ExecStart=
ExecStart=/usr/bin/obs --minimize-to-tray --disable-shutdown-check --startstreaming
